# Combine the related files for a specific platform and MCU.

# Target ECU board design
BOARDCPPSRC = $(BOARDS_DIR)/hellen/hellen128/board_configuration.cpp

BOARDINC = $(BOARDS_DIR)/hellen/hellen128

IS_STM32F429 = yes

# Set this if you want a default engine type other than normal hellen128
ifeq ($(VAR_DEF_ENGINE_TYPE),)
  VAR_DEF_ENGINE_TYPE = -DDEFAULT_ENGINE_TYPE=HELLEN_128_MERCEDES_4_CYL
endif


DDEFS += -DEFI_MAIN_RELAY_CONTROL=TRUE

# Disable serial ports on this board as UART3 causes a DMA conflict with the SD card
DDEFS += -DTS_NO_PRIMARY=1
#DDEFS += -DEFI_CONSOLE_TX_BRAIN_PIN=Gpio::E1 -DEFI_CONSOLE_RX_BRAIN_PIN=Gpio::E0
#DDEFS += -DTS_PRIMARY_PORT=SD8 -DSTM32_SERIAL_USE_UART8=1 -DHAL_USE_SERIAL=TRUE
#DDEFS += -DEFI_USE_UART_DMA=FALSE
#DDEFS += -DSTM32_UART_USE_UART8=TRUE
#DDEFS += -DTS_PRIMARY_PORT=UARTD8


# Add them all together
DDEFS += -DFIRMWARE_ID=\"hellen128\" $(VAR_DEF_ENGINE_TYPE)
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE -DSTM32_ADC_USE_ADC3=TRUE

DDEFS += -DSHORT_BOARD_NAME=hellen128

#Add TS_SECONDAY port
# PE0 and PE1 - UART8
# DDEFS += -DEFI_CONSOLE_TX_BRAIN_PIN=Gpio::E1 -DEFI_CONSOLE_RX_BRAIN_PIN=Gpio::E0
 DDEFS += -DHAL_USE_SERIAL=TRUE
 DDEFS += -DSTM32_SERIAL_USE_UART8=TRUE
 DDEFS += -DTS_SECONDARY_PORT=SD8
 DDEFS += -DEFI_USE_UART_DMA=FALSE
# DDEFS += -DEFI_USE_UART_DMA=FALSE
# DDEFS += -DTS_NO_SECONDARY=TRUE


include $(BOARDS_DIR)/hellen/hellen-common176.mk

