#include "efi_quote.h"

#pragma once

#define META_ENGINE_GENERATED_NAME engine_configuration_generated_structures_
#define META_ENGINE_GENERATED_EXT .h

#define META_ENGINE_GENERATED_H_FILENAME QUOTE(META_ENGINE_GENERATED_NAME SHORT_BOARD_NAME META_ENGINE_GENERATED_EXT)
#include META_ENGINE_GENERATED_H_FILENAME
