#!/bin/bash

# STM32F767 version of the firmware for Nucleo-F767ZI board

SCRIPT_NAME="compile_nucleo_f767.sh"
echo "Entering $SCRIPT_NAME"

export PROJECT_BOARD=nucleo_f767
export PROJECT_CPU=ARCH_STM32F7
export EXTRA_PARAMS="-DDUMMY -DSTM32F767xx \
 -DEFI_INJECTOR_PIN3=GPIO_UNASSIGNED \
 -DFIRMWARE_ID=\\\"nucleo767\\\" \
 -DEFI_COMMUNICATION_PIN=GPIOB_7 \
 -DSTATUS_LOGGING_BUFFER_SIZE=1400 \
 -DLED_CRITICAL_ERROR_BRAIN_PIN=GPIOB_14 \
 -DEFI_ENABLE_ASSERTS=FALSE \
 -DCH_DBG_ENABLE_CHECKS=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE"
export DEBUG_LEVEL_OPT="-O2"

bash ../common_make.sh
