//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen64_miataNA6_94/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::G9,
	Gpio::H15,
	Gpio::D12,
	Gpio::F14,
	Gpio::G2,
	Gpio::G7,
	Gpio::G8,
	Gpio::D14,
	Gpio::D11,
	Gpio::D10,
	Gpio::I8,
	Gpio::C13,
	Gpio::E5,
	Gpio::F12,
	Gpio::I0,
	Gpio::G12,
	Gpio::D9,
	Gpio::C7,
	Gpio::C8,
	Gpio::C6,
}
