package com.rusefi;

public interface UiVersion {
    /**
     * Console version, YYYYMMDD format.
     *
     * Value is generated automatically at build time from the build date
     * (Europe/London, the same timezone gen_signature.sh uses for the firmware
     * signature) into GeneratedUiVersion.java - so every build carries today's
     * date without a manual bump. Rebuild to refresh; do not edit this file.
     *
     * *** BE CAREFUL WE HAVE SEPARATE AUTOUPDATE_VERSION also managed manually ***
     * @see com.rusefi.autoupdate.Autoupdate#AUTOUPDATE_VERSION
     */
    int CONSOLE_VERSION = GeneratedUiVersion.CONSOLE_VERSION;
}
