//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-silver/connectors/alphax-silver-aux.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-silver/connectors/alphax-silver.yaml
#pragma once

#define PIN_X2 TLE9104_2_OUT_3
#define PIN_X3 TLE9104_2_OUT_1
#define PIN_X4 TLE9104_2_OUT_0
#define PIN_X7 MM100_IN_AUX2_ANALOG
#define PIN_X8 MM100_IN_AUX4_ANALOG
#define PIN_X9 MM100_IN_PPS_ANALOG
#define PIN_1A TLE9104_0_OUT_3
#define PIN_2A TLE9104_0_OUT_2
#define PIN_3A TLE9104_0_OUT_1
#define PIN_4A TLE9104_0_OUT_0
#define PIN_5A TLE9104_1_OUT_1
#define PIN_6A TLE9104_1_OUT_2
#define PIN_9A MM100_IN_VBATT
#define PIN_10A MM100_IGN4
#define PIN_11A MM100_IGN3
#define PIN_12A MM100_IGN2
#define PIN_13A MM100_IGN1
#define PIN_14A TLE9104_1_OUT_0
#define PIN_16A_event_inputs MM100_IN_D4
#define PIN_16A_switch_inputs MM100_IN_D4
#define PIN_17A_event_inputs MM100_IN_D3
#define PIN_17A_switch_inputs MM100_IN_D3
#define PIN_16A17A MM100_IN_CAM
#define PIN_18A MM100_IN_TPS_ANALOG
#define PIN_19A MM100_IN_CLT_ANALOG
#define PIN_20A MM100_IN_IAT_ANALOG
#define PIN_On_board_MAP MM100_IN_MAP2_ANALOG
#define PIN_21A MM100_IN_MAP1_ANALOG
#define PIN_22A MM100_IN_AUX1_ANALOG
#define PIN_24A_event_inputs MM100_IN_D2
#define PIN_24A_switch_inputs MM100_IN_D2
#define PIN_25A_event_inputs MM100_IN_D1
#define PIN_25A_switch_inputs MM100_IN_D1
#define PIN_24A25A MM100_IN_CRANK
#define PIN_28A MM100_IN_AUX3_ANALOG
