//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-silver/connectors/alphax-silver.yaml
#pragma once

#define PIN_1A TLE9104_0_OUT_3
#define PIN_9A EFI_ADC_5
#define PIN_16A E15
#define PIN_16A E15
