include $(BOARD_DIR)/../board.mk

DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE

# todo: KNOCK_SPECTROGRAM to use big_buffer
DDEFS += -DKNOCK_SPECTROGRAM=TRUE
DDEFS += -DEFI_USE_COMPRESSED_INI_MSD=TRUE
DDEFS += -DEFI_DYNO_VIEW=TRUE
DDEFS += -DENABLE_PERF_TRACE=TRUE
DDEFS += -DLUA_RX_MAX_FILTER_COUNT=96
DDEFS += -DSTATIC_BOARD_ID=STATIC_BOARD_ID_PROTEUS_F7

DDEFS += -DLUA_USER_HEAP=99000

ifeq ($(EFI_LUA_LOOKUP),)
EFI_LUA_LOOKUP = TRUE
endif
DDEFS += -DEFI_LUA_LOOKUP=$(EFI_LUA_LOOKUP)

# note #define EFI_EMBED_INI_MSD FALSE in F7 features
ifeq ($(DEBUG_LEVEL_OPT),)
	DEBUG_LEVEL_OPT = -Os -ggdb -g
endif