// auto-generated by PinoutLogic.java

#include "pch.h"

const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case GPIOA_0: return "Out 1";
		case GPIOA_1: return "Out 2";
		case GPIOA_10: return "Out 8";
		case GPIOA_2: return "Out 3";
		case GPIOA_3: return "Out 4";
		case GPIOA_8: return "Out 6";
		case GPIOA_9: return "Out 7";
		case GPIOC_9: return "Out 5";
		default: return nullptr;
	}
	return nullptr;
}
