//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/tdg-pdm8/connectors/main.yaml
// auto-generated by PinoutLogic.java based on config/boards/tdg-pdm8/connectors/x3.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::PROTECTED_PIN_7,
	Gpio::PROTECTED_PIN_6,
	Gpio::PROTECTED_PIN_5,
	Gpio::PROTECTED_PIN_4,
	Gpio::PROTECTED_PIN_3,
	Gpio::PROTECTED_PIN_2,
	Gpio::PROTECTED_PIN_1,
	Gpio::PROTECTED_PIN_0,
}
