//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/tdg-pdm8/connectors/tdg-pdm8.yaml
// auto-generated by PinoutLogic.java based on config/boards/tdg-pdm8/connectors/x3.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::PROTECTED_PIN_7, // Out 8
	Gpio::PROTECTED_PIN_6, // Out 7
	Gpio::PROTECTED_PIN_5, // Out 6
	Gpio::PROTECTED_PIN_4, // Out 5
	Gpio::PROTECTED_PIN_3, // Out 4
	Gpio::PROTECTED_PIN_2, // Out 3
	Gpio::PROTECTED_PIN_1, // Out 2
	Gpio::PROTECTED_PIN_0, // Out 1
// "Out 8",
// "Out 7",
// "Out 6",
// "Out 5",
// "Out 4",
// "Out 3",
// "Out 2",
// "Out 1",
}
