//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/core8/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A15: return "Low Side 24 (A15)";
		case Gpio::A8: return "Low Side 20 (A8)";
		case Gpio::B14: return "Low Side 1 (B14 v2.1 ONLY)";
		case Gpio::B15: return "Low Side 2 (B15 v2.1 ONLY)";
		case Gpio::B7: return "DBW Disable (B7)";
		case Gpio::B8: return "DBW Control (B8)";
		case Gpio::B9: return "DBW Direction (B9)";
		case Gpio::C13: return "Digital Input 8 (C13)";
		case Gpio::C6: return "Low Side 18 (C6)";
		case Gpio::C7: return "Low Side 19 (C7)";
		case Gpio::D10: return "Low Side 5 (D10)";
		case Gpio::D11: return "Low Side 6 (D11)";
		case Gpio::D12: return "Low Side 7 (D12)";
		case Gpio::D13: return "Low Side 8 (D13)";
		case Gpio::D14: return "Low Side 9 (D14)";
		case Gpio::D15: return "Low Side 10 (D15)";
		case Gpio::D3: return "Low Side 23 (D3)";
		case Gpio::D4: return "Low Side 22 (D4)";
		case Gpio::D5: return "Low Side 21 (D5)";
		case Gpio::D8: return "Low Side 3 (D8)";
		case Gpio::D9: return "Low Side 4 (D9)";
		case Gpio::E10: return "High Side 10 (E10)";
		case Gpio::E11: return "High Side 5 (E11)";
		case Gpio::E12: return "High Side 4 (E12)";
		case Gpio::E13: return "High Side 3 (E13)";
		case Gpio::E14: return "High Side 2 (E14)";
		case Gpio::E15: return "High Side 1 (E15)";
		case Gpio::E2: return "VR/Hall 1 (E2)";
		case Gpio::E3: return "VR/Hall 2 (E3)";
		case Gpio::E4: return "VR/Hall 3 (E4)";
		case Gpio::E5: return "VR/Hall 4 (E5)";
		case Gpio::E6: return "Digital Input 7 (E6)";
		case Gpio::E7: return "High Side 9 (E7)";
		case Gpio::E8: return "High Side 12 (E8)";
		case Gpio::E9: return "High Side 11 (E9)";
		case Gpio::F0: return "Digital Input 6 (F0)";
		case Gpio::F1: return "Digital Input 5 (F1)";
		case Gpio::F13: return "Low Side 1 (F13)";
		case Gpio::F14: return "Low Side 2 (F14)";
		case Gpio::F15: return "High Side 6 (F15)";
		case Gpio::F2: return "Digital Input 4 (F2)";
		case Gpio::F3: return "Digital Input 3 (F3)";
		case Gpio::F4: return "Digital Input 2 (F4)";
		case Gpio::F5: return "Digital Input 1 (F5)";
		case Gpio::F7: return "StepEr Direction (F7)";
		case Gpio::F8: return "StepEr Control (F8)";
		case Gpio::F9: return "StepEr Disable (F9)";
		case Gpio::G0: return "High Side 7 (G0)";
		case Gpio::G1: return "High Side 8 (G1)";
		case Gpio::G2: return "Low Side 11 (G2)";
		case Gpio::G3: return "Low Side 12 (G3)";
		case Gpio::G4: return "Low Side 13 (G4)";
		case Gpio::G5: return "Low Side 14 (G5)";
		case Gpio::G6: return "Low Side 15 (G6)";
		case Gpio::G7: return "Low Side 16 (G7)";
		case Gpio::G8: return "Low Side 17 (G8)";
		default: return nullptr;
	}
	return nullptr;
}
