// auto-generated by PinoutLogic.java

#include "pch.h"

const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::C13: return "Black A6 - LSU4.9 PIN 5 / Digital Input 8";
		case Gpio::D10: return "Grey A5 - Injector 5";
		case Gpio::D11: return "Grey A6 - Injector 6";
		case Gpio::D12: return "Grey A7 - Injector 7";
		case Gpio::D13: return "Grey A8 - Injector 8";
		case Gpio::D14: return "Grey C8 - Low Side Output";
		case Gpio::D15: return "Black C1 - Low Side Output";
		case Gpio::D8: return "Grey A3 - Injector 3";
		case Gpio::D9: return "Grey A4 - Injector 4";
		case Gpio::E11: return "Grey B5 - Ignition 5";
		case Gpio::E12: return "Grey B4 - Ignition 4";
		case Gpio::E13: return "Grey B3 - Ignition 3";
		case Gpio::E14: return "Grey B2 - Ignition 2";
		case Gpio::E15: return "Grey B1 - Ignition 1";
		case Gpio::E2: return "Camshaft Sensor VR+/Hall";
		case Gpio::E3: return "Crank Sensor VR+/Hall";
		case Gpio::E6: return "Black B6 - LSU4.9 PIN 6 / Digital Input 7";
		case Gpio::F0: return "Black B7 - LSU4.9 PIN 1 / Digital Input 6";
		case Gpio::F1: return "Black A7 - LSU4.9 PIN 2 / Digital Input 5";
		case Gpio::F13: return "Grey A1 - Injector 1";
		case Gpio::F14: return "Grey A2 - Injector 2";
		case Gpio::F15: return "Grey B6 - Ignition 6";
		case Gpio::F3: return "Black B4 - Digital Input 3";
		case Gpio::F4: return "Black B3 - Digital Input 2";
		case Gpio::F5: return "Black B2 - Digital Input 1";
		case Gpio::G0: return "Grey B7 - Ignition 7";
		case Gpio::G1: return "Grey B8 - Ignition 8";
		case Gpio::G2: return "Black B1 - Low Side Output";
		case Gpio::G3: return "Black A1 - Low Side Output";
		case Gpio::G4: return "Black A2 - Low Side Output";
		case Gpio::G5: return "Black A3 - Low Side Output";
		case Gpio::G6: return "Black A4 - Low Side Output / DBW_OUT+";
		case Gpio::G7: return "Black A5 - Low Side Output / DBW_OUT-";
		default: return nullptr;
	}
	return nullptr;
}
