BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp

DDEFS += -DSTATIC_BOARD_ID=STATIC_BOARD_ID_SMALL_CAN_BOARD

#DDEFS += -DEFI_SENT_SUPPORT=TRUE

DDEFS += -DPERSISTENT_LOCATION="__attribute__((section(\".ram1\")))"
DDEFS += -DEFI_SENSOR_CHART=FALSE
DDEFS += -DLUA_USER_HEAP=50000
DDEFS += -DEFI_IDLE_CONTROL=FALSE
DDEFS += -DDL_OUTPUT_BUFFER=5000
DDEFS += -DEFI_ELECTRONIC_THROTTLE_BODY=FALSE
DDEFS += -DEFI_LOGIC_ANALYZER=FALSE
DDEFS += -DEFI_MALFUNCTION_INDICATOR=FALSE
DDEFS += -DEFI_ENGINE_SNIFFER=FALSE
DDEFS += -DEFI_ENGINE_EMULATOR=FALSE
DDEFS += -DEFI_SHAFT_POSITION_INPUT=FALSE
DDEFS += -DEFI_ALTERNATOR_CONTROL=FALSE
# temp DDEFS += -DEFI_ENGINE_CONTROL=FALSE
DDEFS += -DEFI_VVT_PID=FALSE
DDEFS += -DEFI_EMULATE_POSITION_SENSORS=FALSE
DDEFS += -DEFI_MAP_AVERAGING=FALSE
DDEFS += -DEFI_HPFP=FALSE
DDEFS += -DEFI_TOOTH_LOGGER=FALSE
DDEFS += -DRAM_UNUSED_SIZE=100
DDEFS += -DPWM_FREQ_PWM=10000

DDEFS += -DHW_SMALL_CAN_BOARD=1

# CAND1
DDEFS += -DBOOT_COM_CAN_CHANNEL_INDEX=0
DDEFS += -DOPENBLT_CAN_RX_PORT=GPIOB
DDEFS += -DOPENBLT_CAN_RX_PIN=8
DDEFS += -DOPENBLT_CAN_TX_PORT=GPIOB
DDEFS += -DOPENBLT_CAN_TX_PIN=9
DDEFS += -DBOOT_BACKDOOR_ENTRY_TIMEOUT_MS=1000

#Mass Storage
DDEFS += -DEFI_EMBED_INI_MSD=FALSE

#DDEFS += $(PRIMARY_COMMUNICATION_PORT_USART3)

#DDEFS += -DEFI_KLINE=TRUE
DDEFS += -DKLINE_SERIAL_DEVICE_RX=Gpio::С7 -DKLINE_SERIAL_DEVICE_TX=Gpio::С6
DDEFS += -DKLINE_SERIAL_DEVICE=SD6
DDEFS += -DSTM32_SERIAL_USE_USART6=TRUE

include $(BOARDS_DIR)/hellen/hellen-common64.mk
