#!/bin/bash

export EXTRA_PARAMS="\
 -DEFI_HPFP=FALSE \
 -DEFI_ALTERNATOR_CONTROL=FALSE \
 -DEFI_LOGIC_ANALYZER=FALSE \
 -DEFI_TOOTH_LOGGER=FALSE \
 -DEFI_LUA=FALSE -DSHORT_BOARD_NAME=f407-discovery -DSTATIC_BOARD_ID=STATIC_BOARD_ID_F407_DISCOVERY \
 -DRAMDISK_INVALID"
export DEBUG_LEVEL_OPT="-O0 -ggdb -g"
export INCLUDE_ELF=yes
bash ../common_make.sh f407-discovery ARCH_STM32F4
