# funny thing: we reuse board_configuration.cpp from f407-discovery
BOARDCPPSRC = $(BOARD_DIR)/../f407-discovery/board_configuration.cpp

ifeq ($(VAR_DEF_ENGINE_TYPE),)
  VAR_DEF_ENGINE_TYPE = -DDEFAULT_ENGINE_TYPE=engine_type_e::DEFAULT_FRANKENSO
endif

DDEFS += -DFIRMWARE_ID=\"frankenso_na6\"
DDEFS += -DSTATIC_BOARD_ID=STATIC_BOARD_ID_FRANKENSO_NA6
DDEFS += -DHW_NOT_COMMUNITY_FRANKENSO=TRUE

DDEFS += -DRAM_UNUSED_SIZE=200

# TS_SECONDARY_UxART_PORT
DDEFS += -DSTM32_SERIAL_USE_USART3=TRUE -DSTM32_SERIAL_USART3_PRIORITY=2
DDEFS += -DTS_SECONDARY_UxART_PORT=SD3 -DEFI_TS_SECONDARY_IS_SERIAL=TRUE
