#!/usr/bin/env bash

#-DDUMMY -DEFI_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE"

export PROJECT_BOARD="f429-208"
export PROJECT_CPU="ARCH_STM32F4"

# see signature_haba208.h
export SHORT_BOARD_NAME=haba208
