/*
 * RomRaider Open-Source Tuning, Logging and Reflashing
 * Copyright (C) 2006-2013 RomRaider.com
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// DO NOT EDIT.  This file is automatically generated.

package com.romraider;

import javax.swing.ImageIcon;

public final class Version {
    public static final String PRODUCT_NAME = "RomRaider";
    public static final String VERSION = "0.5.8 RC 1 for rusEfi";
    public static final String BUILDNUMBER = "635";
    public static final String SUPPORT_URL = "http://www.rusefi.com";
//    public static final String ROM_REVISION_URL = "http://www.scoobypedia.co.uk/index.php/Knowledge/ECUVersionCompatibilityList";
//    public static final String ECU_DEFS_URL = "http://www.romraider.com/forum/topic360.html";
//    public static final String LOGGER_DEFS_URL = "http://www.romraider.com/forum/topic1642.html";
    public static final String CARS_DEFS_URL = "http://www.romraider.com/forum/topic5792.html";
    public static final String RELEASE_NOTES = "release_notes.txt";
    public static final ImageIcon ABOUT_ICON = new ImageIcon(Version.class.getClass().getResource( "/graphics/romraider-ico-large.gif" ));
    public static final int MIN_LOG_DEF_VERSION = 155;

    private Version() {
    }
}
