//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/subaru_eg33/connectors/A-B59.yaml
// auto-generated by PinoutLogic.java based on config/boards/subaru_eg33/connectors/B-B60.yaml
// auto-generated by PinoutLogic.java based on config/boards/subaru_eg33/connectors/C-B61.yaml
// auto-generated by PinoutLogic.java based on config/boards/subaru_eg33/connectors/D-B62.yaml
// auto-generated by PinoutLogic.java based on config/boards/subaru_eg33/connectors/XP2-AUX0.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::MC33810_0_OUT_2,
	Gpio::MC33810_1_OUT_2,
	Gpio::MC33810_0_OUT_1,
	Gpio::MC33810_1_OUT_0,
	Gpio::MC33810_0_OUT_0,
	Gpio::MC33810_1_OUT_1,
	Gpio::TLE6240_PIN_15,
	Gpio::TLE6240_PIN_4,
	Gpio::TLE6240_PIN_8,
	Gpio::TLE6240_PIN_3,
	Gpio::TLE6240_PIN_12,
	Gpio::TLE6240_PIN_11,
	Gpio::TLE6240_PIN_2,
	Gpio::H7,
	Gpio::TLE6240_PIN_10,
	Gpio::MC33810_0_GD_0,
	Gpio::MC33810_1_GD_2,
	Gpio::MC33810_0_GD_1,
	Gpio::MC33810_1_GD_3,
	Gpio::MC33810_1_GD_1,
	Gpio::TLE6240_PIN_1,
	Gpio::TLE6240_PIN_9,
	Gpio::TLE6240_PIN_7,
	Gpio::TLE6240_PIN_16,
	Gpio::MC33810_0_GD_3,
	Gpio::TLE6240_PIN_6,
	Gpio::TLE6240_PIN_5,
	Gpio::TLE6240_PIN_14,
	Gpio::TLE6240_PIN_13,
}
