include $(BOARD_DIR)/../board.mk

DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE

DDEFS += -DKNOCK_SPECTROGRAM=TRUE
DDEFS += -DEFI_USE_COMPRESSED_INI_MSD=FALSE
DDEFS += -DEFI_DYNO_VIEW=TRUE
DDEFS += -DENABLE_PERF_TRACE=TRUE

# serial ports only on F4
# Hardware serial port on UART 2 -> PD5/PD6
DDEFS += -DSTM32_UART_USE_USART2=TRUE
DDEFS += -DTS_PRIMARY_UxART_PORT=UARTD2
DDEFS += -DEFI_CONSOLE_TX_BRAIN_PIN=Gpio::D5 -DEFI_CONSOLE_RX_BRAIN_PIN=Gpio::D6

DDEFS += -DSTATIC_BOARD_ID=STATIC_BOARD_ID_PROTEUS_F4
DDEFS += -DRAM_UNUSED_SIZE=100