#!/usr/bin/env bash

export EXTRA_PARAMS="\
 -DEFI_HPFP=FALSE \
 -DEFI_ALTERNATOR_CONTROL=FALSE \
 -DEFI_LOGIC_ANALYZER=FALSE \
 -DEFI_ENGINE_SNIFFER=FALSE \
 -DEFI_BOOST_CONTROL=FALSE \
 -DEFI_LAUNCH_CONTROL=FALSE \
 -DEFI_ANTILAG_SYSTEM=FALSE \
 -DEFI_MC33816=FALSE \
 -DEFI_BLUETOOTH_SETUP=FALSE \
 -DEFI_ELECTRONIC_THROTTLE_BODY=FALSE \
 -DEFI_SENSOR_CHART=FALSE \
 -DEFI_TOOTH_LOGGER=FALSE \
 -DEFI_LUA=FALSE \
 -DRAMDISK_INVALID"
export DEBUG_LEVEL_OPT="-O0 -ggdb -g"
export INCLUDE_ELF=yes
export PROJECT_BOARD="proteus"
export PROJECT_CPU="ARCH_STM32F4"
export SHORT_BOARD_NAME=proteus_f4
