#!/bin/bash

export PROJECT_BOARD=proteus
export PROJECT_CPU=ARCH_STM32F4
export EXTRA_PARAMS="-DVR_HW_CHECK_MODE=TRUE -DSHORT_BOARD_NAME=proteus_f4"

export DEFAULT_ENGINE_TYPE=-DDEFAULT_ENGINE_TYPE=PROTEUS_QC_TEST_BOARD

# export DEBUG_LEVEL_OPT="-O0 -ggdb -g3"

bash ../common_make.sh
