/*
 * proteus_meta.h
 *
 * @date Oct 2, 2021
 * @author Andrey Belomutskiy, (c) 2012-2021
 */

#pragma once

#define PROTEUS_LS_1 GPIOD_7
// pin 15/black35
#define PROTEUS_LS_2 GPIOG_9

// pin 4/black35
#define PROTEUS_LS_3 GPIOG_10

// pin 16/black35
#define PROTEUS_LS_4 GPIOG_11

#define PROTEUS_LS_5 GPIOG_12
#define PROTEUS_LS_6 GPIOG_13
#define PROTEUS_LS_7 GPIOG_14
#define PROTEUS_LS_8 GPIOB_4
#define PROTEUS_LS_9 GPIOB_5

// pin 20/black35
#define PROTEUS_LS_10 GPIOB_6
#define PROTEUS_LS_11 GPIOB_7
#define PROTEUS_LS_12 GPIOB_8

// pin 10/black35
#define PROTEUS_LS_13 GPIOB_9
#define PROTEUS_LS_14 GPIOE_0
// pin 12/black35
#define PROTEUS_LS_15 GPIOE_1
// pin 23/black35
#define PROTEUS_LS_16 GPIOE_2

// pin 2/black35
#define PROTEUS_HS_1 GPIOD_4

// pin 1/black35
#define PROTEUS_HS_2 GPIOD_3

// pin 22/black35
#define PROTEUS_HS_3 GPIOC_9
#define PROTEUS_HS_4 GPIOC_8
#define PROTEUS_HS_5 GPIOC_7
#define PROTEUS_HS_6 GPIOG_8
#define PROTEUS_HS_7 GPIOG_7
#define PROTEUS_HS_8 GPIOG_6
#define PROTEUS_HS_9 GPIOG_5
#define PROTEUS_HS_10 GPIOG_4
#define PROTEUS_HS_11 GPIOG_3
#define PROTEUS_HS_12 GPIOG_2

// IAT = Analog Temp 2 = PC5
#define PROTEUS_IN_ANALOG_TEMP_2 EFI_ADC_15
#define PROTEUS_IN_IAT PROTEUS_IN_ANALOG_TEMP_2

// CLT = Analog Temp 3 = PB0
#define PROTEUS_IN_ANALOG_TEMP_3 EFI_ADC_8
#define PROTEUS_IN_CLT PROTEUS_IN_ANALOG_TEMP_3

// MAP = Analog volt 1 = PC0
#define PROTEUS_IN_ANALOG_VOLT_1 EFI_ADC_10
#define PROTEUS_IN_MAP PROTEUS_IN_ANALOG_VOLT_1

// TPS = Analog volt 2 = PC1
#define PROTEUS_IN_ANALOG_VOLT_2 EFI_ADC_11
#define PROTEUS_IN_TPS PROTEUS_IN_ANALOG_VOLT_2

#define PROTEUS_VR_1 GPIOE_7
#define PROTEUS_VR_2 GPIOE_8

#define PROTEUS_DIGITAL_1 GPIOC_6
#define PROTEUS_DIGITAL_2 GPIOE_11
#define PROTEUS_DIGITAL_3 GPIOE_12
#define PROTEUS_DIGITAL_4 GPIOE_14
#define PROTEUS_DIGITAL_5 GPIOE_13
#define PROTEUS_DIGITAL_6 GPIOE_15
