//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/harley81/connectors/harley81.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::G3,
	Gpio::C7,
	Gpio::D15,
	Gpio::D14,
	Gpio::G7,
	Gpio::G8,
	Gpio::G11,
	Gpio::C13,
	Gpio::D2,
	Gpio::E5,
	Gpio::G14,
	Gpio::G5,
}
