//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/harley81/connectors/harley81.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::G3, // auxMain
	Gpio::C7, // auxWastegate
	Gpio::D15, // 1 Right Oil Cooling
	Gpio::D14, // 4 Left Oil Fan
	Gpio::G7, // 6 Front Injector 1
	Gpio::G8, // 7 Rear Injector 2
	Gpio::G11, // 8 Rear ACR
	Gpio::C13, // 24 Front Coil 1
	Gpio::D2, // 25 Front ACR
	Gpio::E5, // 43 Rear Coil 2
	Gpio::G14, // 61 Reverse Gear
	Gpio::G5, // 63 Cooling Pump
}
