<Waves>
  <Wave>
    <Name>Start1</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>6</Ordinal>
    <Direction>Input</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Flag2Out</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>0</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Flag1Out</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>1</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Flag0Out</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>2</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Dac1</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>43</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Hs1Command</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>4</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Hs2Command</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>5</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Ls1Command</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>9</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Cnt1</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>0</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Cnt2</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>1</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Cnt3</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>2</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Cnt4</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>3</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Eoc1</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>4</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Eoc2</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>5</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Eoc3</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>6</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Eoc4</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>7</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>TerminalCount1</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>8</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>TerminalCount2</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>9</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>TerminalCount3</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>10</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>TerminalCount4</Name>
    <Path>
      <PathElement>PT2001</PathElement>
      <PathElement>Injection Channel 1</PathElement>
      <PathElement>ChSequencers</PathElement>
      <PathElement>MicroMachineSeq0</PathElement>
      <PathElement>Counters</PathElement>
    </Path>
    <Ordinal>11</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Oaout1FlagOut</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>16</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
  <Wave>
    <Name>Flag0Out</Name>
    <Path>
      <PathElement>PT2001</PathElement>
    </Path>
    <Ordinal>2</Ordinal>
    <Direction>Output</Direction>
    <Radix>Decimal</Radix>
  </Wave>
</Waves>