TESTS_SRC_CPP = \
	tests/trigger/test_symmetrical_crank.cpp \
	tests/trigger/test_trigger_decoder.cpp \
	tests/trigger/test_trigger_noiseless.cpp \
	tests/trigger/test_trigger_multi_sync.cpp \
	tests/trigger/test_miata_na_tdc.cpp \
	tests/trigger/test_cam_vvt_input.cpp \
	tests/trigger/test_2jz_vvt.cpp \
	tests/trigger/test_real_cranking_miata_NA.cpp \
	tests/trigger/test_real_cranking_miata_na6.cpp \
	tests/trigger/test_real_cranking_nissan_vq40.cpp \
	tests/trigger/test_real_volkswagen.cpp \
	tests/trigger/test_real_nb2_cranking.cpp \
	tests/trigger/test_rpm_multiplier.cpp \
	tests/trigger/test_quad_cam.cpp \
	tests/trigger/test_nissan_vq_vvt.cpp \
	tests/trigger/test_override_gaps.cpp \
	tests/trigger/test_injection_scheduling.cpp \
	tests/ignition_injection/injection_mode_transition.cpp \
	tests/ignition_injection/test_startOfCrankingPrimingPulse.cpp \
	tests/ignition_injection/test_multispark.cpp \
	tests/ignition_injection/test_ignition_scheduling.cpp \
	tests/ignition_injection/test_fuelCut.cpp \
	tests/ignition_injection/test_fuel_computer.cpp \
	tests/ignition_injection/test_injector_model.cpp \
	tests/lua/test_lua_basic.cpp \
	tests/lua/test_lua_hooks.cpp \
	tests/sensor/test_cj125.cpp \
	tests/test_change_engine_type.cpp \
	tests/util/test_scaled_channel.cpp \
	tests/util/test_timer.cpp \
	tests/system/test_periodic_thread_controller.cpp \
	tests/test_util.cpp \
	tests/test_start_stop.cpp \
	tests/test_hardware_reinit.cpp \
	tests/test_ion.cpp \
	tests/test_aux_valves.cpp \
	tests/test_hip9011.cpp \
	tests/test_engine_math.cpp \
	tests/test_fasterEngineSpinningUp.cpp \
	tests/test_dwell_corner_case_issue_796.cpp \
	tests/test_idle_controller.cpp \
	tests/test_issue_898.cpp \
	tests/test_etb.cpp \
	tests/test_dc_motor.cpp \
	tests/test_fan_control.cpp \
	tests/test_vvt.cpp \
	tests/test_launch.cpp \
	tests/test_fuel_map.cpp \
	tests/ignition_injection/test_fuel_wall_wetting.cpp \
	tests/test_one_cylinder_logic.cpp \
	tests/test_tunerstudio.cpp \
	tests/test_pwm_generator.cpp \
	tests/test_logic_expression.cpp \
	tests/test_log_buffer.cpp \
	tests/test_signal_executor.cpp \
	tests/test_cpp_memory_layout.cpp \
	tests/test_sensors.cpp \
	tests/test_pid_auto.cpp \
	tests/test_pid.cpp \
	tests/test_accel_enrichment.cpp \
	tests/test_tacho.cpp \
	tests/test_gpiochip.cpp \
	tests/test_deadband.cpp \
	tests/test_knock.cpp \
	tests/sensor/basic_sensor.cpp \
	tests/sensor/func_sensor.cpp \
	tests/sensor/function_pointer_sensor.cpp \
	tests/sensor/mock_sensor.cpp \
	tests/sensor/sensor_reader.cpp \
	tests/sensor/lin_func.cpp \
	tests/sensor/resist_func.cpp \
	tests/sensor/therm_func.cpp \
	tests/sensor/func_chain.cpp \
	tests/sensor/redundant.cpp \
	tests/sensor/test_sensor_init.cpp \
	tests/sensor/table_func.cpp \
	tests/util/test_closed_loop_controller.cpp \
	tests/test_stft.cpp \
	tests/test_boost.cpp \
	tests/test_gppwm.cpp \
	tests/test_fuel_math.cpp \
	tests/test_binary_log.cpp \
	tests/test_dynoview.cpp \
	tests/test_gpio.cpp \
	tests/test_limp.cpp \
	tests/trigger/test_all_triggers.cpp \
	tests/test_stepper.cpp \
	tests/sensor/test_frequency_sensor.cpp \
	tests/sensor/test_turbocharger_speed_converter.cpp \
	tests/sensor/test_vehicle_speed_converter.cpp
