//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen121vag/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::MM176_OUT_PWM8, // auxP6 output
	Gpio::MM176_OUT_IO5, // auxP7 output
	Gpio::MM176_OUT_IO6, // auxP8 output
	Gpio::MM176_OUT_PWM17, // Main Relay
	Gpio::F13, // 19 - INJ 7
	Gpio::F14, // 24 - INJ 8
	Gpio::D13, // 37 - TACH
	Gpio::G4, // 47 - CEL
	Gpio::MM176_GP13, // 65 - Fuel Pump
	Gpio::D10, // 88 - INJ_4
	Gpio::G8, // 89 - INJ_2
	Gpio::G7, // 96 - INJ_1
	Gpio::D11, // 97 - INJ_3
	Gpio::D14, // 105 - IDLE rev A,B
	Gpio::G5, // 105 - IDLE rev C+
	Gpio::F12, // 112 INJ 6
	Gpio::D9, // 113 INJ 5
	Gpio::E5, // 7 - IGN_2
	Gpio::I6, // 8 - IGN_7
	Gpio::MM176_OUT_PWM5, // 18 - VVT2 B1
	Gpio::I0, // 22 - VVT1 1
	Gpio::MM176_OUT_PWM7, // OUT_FUEL_CONSUMPTION
	Gpio::E3, // 94 - IGN_4
	Gpio::I7, // 95 - IGN_8
	Gpio::C1, // 101 - MAP2
	Gpio::I8, // 102 - IGN_1
	Gpio::E2, // 103 - IGN_5
	Gpio::A9, // 104 Wastegate
	Gpio::I5, // 110 - IGN_6
	Gpio::E4, // 111 - IGN_3
	Gpio::MM176_OUT_IO7, // 115 - VVT1_2
	Gpio::C6, // 117 ETB_OUT+
	Gpio::C7, // 118 ETB_OUT-
	Gpio::C8, // 120 - VVT2 B2
// "auxP6 output",
// "auxP7 output",
// "auxP8 output",
// "Main Relay",
// "19 - INJ 7",
// "24 - INJ 8",
// "37 - TACH",
// "47 - CEL",
// "65 - Fuel Pump",
// "88 - INJ_4",
// "89 - INJ_2",
// "96 - INJ_1",
// "97 - INJ_3",
// "105 - IDLE rev A,B",
// "105 - IDLE rev C+",
// "112 INJ 6",
// "113 INJ 5",
// "7 - IGN_2",
// "8 - IGN_7",
// "18 - VVT2 B1",
// "22 - VVT1 1",
// "OUT_FUEL_CONSUMPTION",
// "94 - IGN_4",
// "95 - IGN_8",
// "101 - MAP2",
// "102 - IGN_1",
// "103 - IGN_5",
// "104 Wastegate",
// "110 - IGN_6",
// "111 - IGN_3",
// "115 - VVT1_2",
// "117 ETB_OUT+",
// "118 ETB_OUT-",
// "120 - VVT2 B2",
}
