//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/epicECU/connectors/epicECU.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::EPICECU_INJ1, // Injector  1
	Gpio::EPICECU_INJ2, // Injector  2
	Gpio::EPICECU_INJ3, // Injector  3
	Gpio::EPICECU_INJ4, // Injector  4
	Gpio::EPICECU_INJ5, // Injector  5
	Gpio::EPICECU_INJ6, // Injector  6
	Gpio::EPICECU_INJ7, // Injector  7
	Gpio::EPICECU_INJ8, // Injector  8
	Gpio::EPICECU_INJ9, // Injector  9
	Gpio::EPICECU_INJ10, // Injector 10
	Gpio::EPICECU_INJ11, // Injector 11
	Gpio::EPICECU_INJ12, // Injector 12
	Gpio::EPICECU_LS1, // Low Side Output  1
	Gpio::EPICECU_LS2, // Low Side Output  2
	Gpio::EPICECU_LS3, // Low Side Output  3
	Gpio::EPICECU_LS4, // Low Side Output  4
	Gpio::EPICECU_LS5, // Low Side Output  5
	Gpio::EPICECU_LS6, // Low Side Output  6
	Gpio::EPICECU_LS7, // Low Side Output  7
	Gpio::EPICECU_LS8, // Low Side Output  8
	Gpio::EPICECU_LS9, // Low Side Output  9
	Gpio::EPICECU_LS10, // Low Side Output 10
	Gpio::EPICECU_LS11, // Low Side Output 11
	Gpio::EPICECU_LS12, // Low Side Output 12
	Gpio::EPICECU_LS13, // Low Side Output 13
	Gpio::EPICECU_LS14, // Low Side Output 14
	Gpio::EPICECU_LS15, // Low Side Output 15
	Gpio::EPICECU_LS16, // Low Side Output 16
	Gpio::EPICECU_LS17, // Low Side Output 17
	Gpio::EPICECU_LS18, // Low Side Output 18
	Gpio::EPICECU_LS19, // Low Side Output 19
	Gpio::EPICECU_LS20, // Tachometer Output
	Gpio::EPICECU_HS1, // High Side Output 1
	Gpio::EPICECU_HS2, // High Side Output 2
	Gpio::EPICECU_HS3, // High Side Output 3
	Gpio::EPICECU_HS4, // High Side Output 4
	Gpio::EPICECU_IGN1, // Ignition Output  1
	Gpio::EPICECU_IGN2, // Ignition Output  2
	Gpio::EPICECU_IGN3, // Ignition Output  3
	Gpio::EPICECU_IGN4, // Ignition Output  4
	Gpio::EPICECU_IGN5, // Ignition Output  5
	Gpio::EPICECU_IGN6, // Ignition Output  6
	Gpio::EPICECU_IGN7, // Ignition Output  7
	Gpio::EPICECU_IGN8, // Ignition Output  8
	Gpio::EPICECU_IGN9, // Ignition Output  9
	Gpio::EPICECU_IGN10, // Ignition Output 10
	Gpio::EPICECU_IGN11, // Ignition Output 11
	Gpio::EPICECU_IGN12, // Ignition Output 12
// "Injector  1",
// "Injector  2",
// "Injector  3",
// "Injector  4",
// "Injector  5",
// "Injector  6",
// "Injector  7",
// "Injector  8",
// "Injector  9",
// "Injector 10",
// "Injector 11",
// "Injector 12",
// "Low Side Output  1",
// "Low Side Output  2",
// "Low Side Output  3",
// "Low Side Output  4",
// "Low Side Output  5",
// "Low Side Output  6",
// "Low Side Output  7",
// "Low Side Output  8",
// "Low Side Output  9",
// "Low Side Output 10",
// "Low Side Output 11",
// "Low Side Output 12",
// "Low Side Output 13",
// "Low Side Output 14",
// "Low Side Output 15",
// "Low Side Output 16",
// "Low Side Output 17",
// "Low Side Output 18",
// "Low Side Output 19",
// "Tachometer Output",
// "High Side Output 1",
// "High Side Output 2",
// "High Side Output 3",
// "High Side Output 4",
// "Ignition Output  1",
// "Ignition Output  2",
// "Ignition Output  3",
// "Ignition Output  4",
// "Ignition Output  5",
// "Ignition Output  6",
// "Ignition Output  7",
// "Ignition Output  8",
// "Ignition Output  9",
// "Ignition Output 10",
// "Ignition Output 11",
// "Ignition Output 12",
}
