//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen-honda-k/connectors/main.yaml
#pragma once

#define PIN_auxhigh1 H144_OUT_IO5
#define PIN_auxpp1 H144_OUT_IO11
#define PIN_A7 H144_IN_RES1
#define PIN_A12 H144_LS_6
#define PIN_A15 H144_IN_TPS
#define PIN_A18 H144_IN_VSS
#define PIN_A19 H144_IN_MAP1
#define PIN_A25 H144_IN_RES3
#define PIN_A26 H144_IN_RES2
#define PIN_A27 H144_IGN_4
#define PIN_A28 H144_IGN_3
#define PIN_A29 H144_IGN_2
#define PIN_A30 H144_IGN_1
#define PIN_B2 H144_LS_4
#define PIN_B3 H144_LS_3
#define PIN_B4 H144_LS_2
#define PIN_B5 H144_LS_1
#define PIN_B6 H144_OUT_IO12
#define PIN_B7 H144_LS_8
#define PIN_B8 H144_IN_CLT
#define PIN_B15 H144_OUT_IO6
#define PIN_B17 H144_IN_IAT
#define PIN_B18 H144_OUT_IO9
#define PIN_B21 H144_OUT_PWM6
#define PIN_B22 H144_LS_7
#define PIN_B23 H144_OUT_PWM5
#define PIN_C8 H144_IN_AUX3_ANALOG
#define PIN_C9 H144_IN_AUX2_ANALOG
#define PIN_C10 H144_IN_AUX1_ANALOG
#define PIN_C11 H144_OUT_PWM8
#define PIN_C12 H144_OUT_PWM7
#define PIN_C13 H144_OUT_PWM3
#define PIN_C18_event_inputs H144_IN_SENS3
#define PIN_C18_switch_inputs H144_IN_SENS3
#define PIN_C19_event_inputs H144_IN_SENS2
#define PIN_C19_switch_inputs H144_IN_SENS2
#define PIN_C21_event_inputs H144_IN_SENS1
#define PIN_C21_switch_inputs H144_IN_SENS1
#define PIN_E1 H144_OUT_IO13
#define PIN_E7 H144_OUT_IO3
#define PIN_E9 H144_IN_VBATT
#define PIN_E18 H144_LS_5
#define PIN_E22 H144_IN_CAM
#define PIN_E26 H144_OUT_IO10
#define PIN_E31 H144_OUT_IO7
