//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen-honda-k/connectors/main.yaml
#pragma once

#define PIN_auxhigh1 D2
#define PIN_A7 F9
#define PIN_A15 EFI_ADC_4
#define PIN_C18 F5
