//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-4K-GDI/connectors/gdi-A.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-4K-GDI/connectors/gdi-B.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::H144_LS_4, // 3A GDI Injector 4
	Gpio::H144_LS_3, // 5A GDI Injector 3
	Gpio::H144_LS_2, // 7A GDI Injector 2
	Gpio::H144_LS_1, // 9A GDI Injector 1
	Gpio::TLE9104_3_OUT_0, // 33A Wastegate Solenoid
	Gpio::TLE9104_3_OUT_1, // 34A AC Control
	Gpio::TLE9104_0_OUT_3, // 1B Port injector 4
	Gpio::TLE9104_0_OUT_2, // 2B Port injector 3
	Gpio::TLE9104_0_OUT_1, // 3B Port injector 2
	Gpio::TLE9104_0_OUT_0, // 4B Port injector 1
	Gpio::TLE9104_1_OUT_0, // 5B Main Relay Control
	Gpio::TLE9104_1_OUT_1, // 7B Fuel Pump
	Gpio::TLE9104_1_OUT_2, // 8B Fan 1
	Gpio::TLE9104_1_OUT_3, // 9B Fan 2
	Gpio::TLE9104_2_OUT_0, // 29B VVT1
	Gpio::TLE9104_2_OUT_1, // 30B VVT2
	Gpio::TLE9104_2_OUT_2, // 31B VVT3
	Gpio::TLE9104_2_OUT_3, // 32B VVT4
	Gpio::H144_LS_6, // HPFP Positive
	Gpio::H144_LS_5, // HPFP Positive_5
	Gpio::H144_IGN_4, // 11A Ignition 4
	Gpio::H144_IGN_3, // 12A Ignition 3
	Gpio::H144_IGN_2, // 13A Ignition 2
	Gpio::H144_IGN_1, // 14A Ignition 1
// "3A GDI Injector 4",
// "5A GDI Injector 3",
// "7A GDI Injector 2",
// "9A GDI Injector 1",
// "33A Wastegate Solenoid",
// "34A AC Control",
// "1B Port injector 4",
// "2B Port injector 3",
// "3B Port injector 2",
// "4B Port injector 1",
// "5B Main Relay Control",
// "7B Fuel Pump",
// "8B Fan 1",
// "9B Fan 2",
// "29B VVT1",
// "30B VVT2",
// "31B VVT3",
// "32B VVT4",
// "HPFP Positive",
// "HPFP Positive_5",
// "11A Ignition 4",
// "12A Ignition 3",
// "13A Ignition 2",
// "14A Ignition 1",
}
