//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-4K-GDI/connectors/gdi-A.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-4K-GDI/connectors/gdi-B.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::H144_IGN_4, // 11A Ignition 4
	Gpio::H144_IGN_3, // 12A Ignition 3
	Gpio::H144_IGN_2, // 13A Ignition 2
	Gpio::H144_IGN_1, // 14A Ignition 1
// "11A Ignition 4",
// "12A Ignition 3",
// "13A Ignition 2",
// "14A Ignition 1",
}
