//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-4K-GDI/connectors/gdi-A.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-4K-GDI/connectors/gdi-B.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::C13: return "14A Ignition 1";
		case Gpio::E3: return "11A Ignition 4";
		case Gpio::E4: return "12A Ignition 3";
		case Gpio::E5: return "13A Ignition 2";
		case Gpio::TLE9104_0_OUT_0: return "4B Port injector 1";
		case Gpio::TLE9104_0_OUT_1: return "3B Port injector 2";
		case Gpio::TLE9104_0_OUT_2: return "2B Port injector 3";
		case Gpio::TLE9104_0_OUT_3: return "1B Port injector 4";
		case Gpio::TLE9104_1_OUT_0: return "5B Main Relay Control";
		case Gpio::TLE9104_1_OUT_1: return "7B Fuel Pump";
		case Gpio::TLE9104_1_OUT_2: return "8B Fan 1";
		case Gpio::TLE9104_1_OUT_3: return "9B Fan 2";
		case Gpio::TLE9104_2_OUT_0: return "29B VVT1";
		case Gpio::TLE9104_2_OUT_1: return "30B VVT2";
		case Gpio::TLE9104_2_OUT_2: return "31B VVT3";
		case Gpio::TLE9104_2_OUT_3: return "32B VVT4";
		default: return nullptr;
	}
	return nullptr;
}
