@echo off

echo Starting compilation for Discovery-407

rem set PROJECT_BOARD=Prometheus
rem set PROMETHEUS_BOARD=405
rem set EXTRA_PARAMS=-DDUMMY -DSTM32F405xx -DEFI_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_CHECKS=FALSE -DCH_DBG_ENABLE_TRACE=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE
set EXTRA_PARAMS=-DDUMMY -DEFI_BOOTLOADER -DBOARD_TLE8888_COUNT=0
set BOOTLOADER_CODE_DESTINATION_PATH=".."
set BOOTLOADER_COMMENT="/*F4discovery*/"
rem set DEBUG_LEVEL_OPT="-O2"

call !compile_bootloader.bat -r

rem Clean up so that no one inherits this value
set PROJECT_BOARD=
set EXTRA_PARAMS=
set DEBUG_LEVEL_OPT=
