@echo off

echo Starting compilation for Prometheus-405

set PROJECT_BOARD=Prometheus
set PROMETHEUS_BOARD=405
set EXTRA_PARAMS=-DDUMMY -DSTM32F405xx -DEFI_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_CHECKS=FALSE -DCH_DBG_ENABLE_TRACE=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE
set BOOTLOADER_CODE_DESTINATION_PATH="../Prometheus/405"
set DEBUG_LEVEL_OPT="-O2"

call !compile_bootloader.bat -r

