@echo off

echo Starting compilation for Prometheus-405

set PROJECT_BOARD=prometheus/f405
set PROMETHEUS_BOARD=405
set EXTRA_PARAMS=-DDUMMY ^
 -DEFI_BOOTLOADER ^
 -DSTM32F405xx ^
 -DEFI_ENABLE_ASSERTS=FALSE ^
 -DCH_DBG_ENABLE_CHECKS=FALSE ^
 -DCH_DBG_ENABLE_ASSERTS=FALSE ^
 -DCH_DBG_ENABLE_STACK_CHECK=FALSE ^
 -DCH_DBG_FILL_THREADS=FALSE ^
 -DBOARD_TLE8888_COUNT=0 ^
 -DBOARD_TLE6240_COUNT=0 ^
 -DBOARD_MC33972_COUNT=0 ^
 -DCH_DBG_THREADS_PROFILING=FALSE
set BOOTLOADER_CODE_DESTINATION_PATH="../Prometheus/405"
set DEBUG_LEVEL_OPT="-O2"

call !compile_bootloader.bat -r
