#!/bin/bash

echo "Starting compilation for Discovery-407"

# set PROJECT_BOARD=Prometheus
# set PROMETHEUS_BOARD=405
# set EXTRA_PARAMS=-DDUMMY -DSTM32F405xx -DEFI_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_CHECKS=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE
export EXTRA_PARAMS="-DDUMMY -DEFI_BOOTLOADER \
 -DCH_DBG_ENABLE_STACK_CHECK=FALSE \
 -DBOARD_TLE8888_COUNT=0 \
 -DBOARD_TLE6240_COUNT=0 \
 -DBOARD_MC33972_COUNT=0"
export BOOTLOADER_CODE_DESTINATION_PATH=".."
export BOOTLOADER_COMMENT="/*F4discovery*/"
# set DEBUG_LEVEL_OPT="-O2"

bash compile_bootloader.sh
