#!/bin/bash

DEFAULT_ENGINE_TYPE=-DDEFAULT_ENGINE_TYPE=FRANKENSO_MIATA_NA6_VAF
FW_ID_ENV=frankensoNA6

export EXTRA_PARAMS="-DDUMMY \
 -DSHORT_BOARD_NAME=frankenso_na6 \
 -DHAL_TRIGGER_USE_PAL=TRUE \
 -DEFI_ICU_INPUTS=FALSE \
 -DHAL_USE_ICU=FALSE \
 -DEFI_LOGIC_ANALYZER=FALSE \
 "

bash ../common_make.sh

