#include "global.h"
#include "rusefi_hw_enums.h"
// was generated automatically by rusEFI tool  from rusefi_hw_enums.h // by enum2string.jar tool on Sat Apr 30 02:29:49 UTC 2022
// see also gen_config_and_enums.bat



const char *getGpio(Gpio value){
switch(value) {
case Gpio::A0:
  return "A0";
case Gpio::A1:
  return "A1";
case Gpio::A10:
  return "A10";
case Gpio::A11:
  return "A11";
case Gpio::A12:
  return "A12";
case Gpio::A13:
  return "A13";
case Gpio::A14:
  return "A14";
case Gpio::A15:
  return "A15";
case Gpio::A16:
  return "A16";
case Gpio::A17:
  return "A17";
case Gpio::A2:
  return "A2";
case Gpio::A3:
  return "A3";
case Gpio::A4:
  return "A4";
case Gpio::A5:
  return "A5";
case Gpio::A6:
  return "A6";
case Gpio::A7:
  return "A7";
case Gpio::A8:
  return "A8";
case Gpio::A9:
  return "A9";
case Gpio::B0:
  return "B0";
case Gpio::B1:
  return "B1";
case Gpio::B10:
  return "B10";
case Gpio::B11:
  return "B11";
case Gpio::B12:
  return "B12";
case Gpio::B13:
  return "B13";
case Gpio::B14:
  return "B14";
case Gpio::B15:
  return "B15";
case Gpio::B16:
  return "B16";
case Gpio::B17:
  return "B17";
case Gpio::B2:
  return "B2";
case Gpio::B3:
  return "B3";
case Gpio::B4:
  return "B4";
case Gpio::B5:
  return "B5";
case Gpio::B6:
  return "B6";
case Gpio::B7:
  return "B7";
case Gpio::B8:
  return "B8";
case Gpio::B9:
  return "B9";
case Gpio::C0:
  return "C0";
case Gpio::C1:
  return "C1";
case Gpio::C10:
  return "C10";
case Gpio::C11:
  return "C11";
case Gpio::C12:
  return "C12";
case Gpio::C13:
  return "C13";
case Gpio::C14:
  return "C14";
case Gpio::C15:
  return "C15";
case Gpio::C16:
  return "C16";
case Gpio::C17:
  return "C17";
case Gpio::C2:
  return "C2";
case Gpio::C3:
  return "C3";
case Gpio::C4:
  return "C4";
case Gpio::C5:
  return "C5";
case Gpio::C6:
  return "C6";
case Gpio::C7:
  return "C7";
case Gpio::C8:
  return "C8";
case Gpio::C9:
  return "C9";
case Gpio::CAN_PIN_0:
  return "CAN_PIN_0";
case Gpio::CAN_PIN_1:
  return "CAN_PIN_1";
case Gpio::CAN_PIN_2:
  return "CAN_PIN_2";
case Gpio::CAN_PIN_3:
  return "CAN_PIN_3";
case Gpio::CAN_PIN_4:
  return "CAN_PIN_4";
case Gpio::CAN_PIN_5:
  return "CAN_PIN_5";
case Gpio::CAN_PIN_6:
  return "CAN_PIN_6";
case Gpio::CAN_PIN_7:
  return "CAN_PIN_7";
case Gpio::D0:
  return "D0";
case Gpio::D1:
  return "D1";
case Gpio::D10:
  return "D10";
case Gpio::D11:
  return "D11";
case Gpio::D12:
  return "D12";
case Gpio::D13:
  return "D13";
case Gpio::D14:
  return "D14";
case Gpio::D15:
  return "D15";
case Gpio::D16:
  return "D16";
case Gpio::D17:
  return "D17";
case Gpio::D2:
  return "D2";
case Gpio::D3:
  return "D3";
case Gpio::D4:
  return "D4";
case Gpio::D5:
  return "D5";
case Gpio::D6:
  return "D6";
case Gpio::D7:
  return "D7";
case Gpio::D8:
  return "D8";
case Gpio::D9:
  return "D9";
case Gpio::E0:
  return "E0";
case Gpio::E1:
  return "E1";
case Gpio::E10:
  return "E10";
case Gpio::E11:
  return "E11";
case Gpio::E12:
  return "E12";
case Gpio::E13:
  return "E13";
case Gpio::E14:
  return "E14";
case Gpio::E15:
  return "E15";
case Gpio::E16:
  return "E16";
case Gpio::E17:
  return "E17";
case Gpio::E2:
  return "E2";
case Gpio::E3:
  return "E3";
case Gpio::E4:
  return "E4";
case Gpio::E5:
  return "E5";
case Gpio::E6:
  return "E6";
case Gpio::E7:
  return "E7";
case Gpio::E8:
  return "E8";
case Gpio::E9:
  return "E9";
case Gpio::Invalid:
  return "Invalid";
case Gpio::TLE6240_PIN_1:
  return "TLE6240_PIN_1";
case Gpio::TLE6240_PIN_10:
  return "TLE6240_PIN_10";
case Gpio::TLE6240_PIN_11:
  return "TLE6240_PIN_11";
case Gpio::TLE6240_PIN_12:
  return "TLE6240_PIN_12";
case Gpio::TLE6240_PIN_13:
  return "TLE6240_PIN_13";
case Gpio::TLE6240_PIN_14:
  return "TLE6240_PIN_14";
case Gpio::TLE6240_PIN_15:
  return "TLE6240_PIN_15";
case Gpio::TLE6240_PIN_16:
  return "TLE6240_PIN_16";
case Gpio::TLE6240_PIN_2:
  return "TLE6240_PIN_2";
case Gpio::TLE6240_PIN_3:
  return "TLE6240_PIN_3";
case Gpio::TLE6240_PIN_4:
  return "TLE6240_PIN_4";
case Gpio::TLE6240_PIN_5:
  return "TLE6240_PIN_5";
case Gpio::TLE6240_PIN_6:
  return "TLE6240_PIN_6";
case Gpio::TLE6240_PIN_7:
  return "TLE6240_PIN_7";
case Gpio::TLE6240_PIN_8:
  return "TLE6240_PIN_8";
case Gpio::TLE6240_PIN_9:
  return "TLE6240_PIN_9";
case Gpio::Unassigned:
  return "Unassigned";
  }
 return NULL;
}
const char *getAdc_channel_e(adc_channel_e value){
switch(value) {
case EFI_ADC_0:
  return "EFI_ADC_0";
case EFI_ADC_1:
  return "EFI_ADC_1";
case EFI_ADC_10:
  return "EFI_ADC_10";
case EFI_ADC_11:
  return "EFI_ADC_11";
case EFI_ADC_12:
  return "EFI_ADC_12";
case EFI_ADC_13:
  return "EFI_ADC_13";
case EFI_ADC_14:
  return "EFI_ADC_14";
case EFI_ADC_15:
  return "EFI_ADC_15";
case EFI_ADC_2:
  return "EFI_ADC_2";
case EFI_ADC_3:
  return "EFI_ADC_3";
case EFI_ADC_4:
  return "EFI_ADC_4";
case EFI_ADC_5:
  return "EFI_ADC_5";
case EFI_ADC_6:
  return "EFI_ADC_6";
case EFI_ADC_7:
  return "EFI_ADC_7";
case EFI_ADC_8:
  return "EFI_ADC_8";
case EFI_ADC_9:
  return "EFI_ADC_9";
case EFI_ADC_ERROR:
  return "EFI_ADC_ERROR";
case EFI_ADC_LAST_CHANNEL:
  return "EFI_ADC_LAST_CHANNEL";
case EFI_ADC_NONE:
  return "EFI_ADC_NONE";
  }
 return NULL;
}
const char *getPin_mode_e(pin_mode_e value){
switch(value) {
case PO_DEFAULT:
  return "PO_DEFAULT";
case PO_OPENDRAIN:
  return "PO_OPENDRAIN";
case PO_PULLDOWN:
  return "PO_PULLDOWN";
case PO_PULLUP:
  return "PO_PULLUP";
  }
 return NULL;
}
