
BOARDCPPSRC = $(PROJECT_DIR)/config/boards/tdg-pdm8/board_configuration.cpp

PROJECT_CPU = ARCH_STM32F4

DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::C11

# No serial ports for now
DDEFS += -DTS_NO_PRIMARY=TRUE -DTS_NO_SECONDARY=TRUE

# No USB
DDEFS += -DEFI_USB_SERIAL=FALSE

# We're running on TDG PDM hardware!
DDEFS += -DHW_TDG_PDM8=1

DDEFS += -DFIRMWARE_ID=\"tdg-pdm8\" -DSHORT_BOARD_NAME=tdg-pdm8
DDEFS += -DDEFAULT_ENGINE_TYPE=MINIMAL_PINS
