/**
 * @file efifeatures.h
 *
 * @date Mar 7, 2014
 * @author Andrey Belomutskiy, (c) 2012-2020
 */

#pragma once

#include "rusefi_true.h"

#define EFI_ENABLE_ASSERTS TRUE

#define EFI_EMULATE_POSITION_SENSORS TRUE

#define EFI_VEHICLE_SPEED TRUE

#define EFI_ENGINE_SNIFFER TRUE

#define EFI_PRINTF_FUEL_DETAILS TRUE

#define EFI_CJ125 TRUE

#define ENABLE_PERF_TRACE FALSE

#define EFI_TOOTH_LOGGER TRUE

#define EFI_LAUNCH_CONTROL TRUE

#define EFI_DYNO_VIEW TRUE

#define EFI_BOOST_CONTROL TRUE

#define EFI_IDLE_CONTROL TRUE

#define EFI_ELECTRONIC_THROTTLE_BODY TRUE

#define SPARK_EXTREME_LOGGING TRUE

#define EFI_ENABLE_MOCK_ADC TRUE

#define EFI_ENABLE_CRITICAL_ENGINE_STOP TRUE
#define EFI_ENABLE_ENGINE_WARNING TRUE

#define EFI_GPIO_HARDWARE TRUE

#define FUEL_MATH_EXTREME_LOGGING TRUE

#define EFI_DEFAILED_LOGGING FALSE

#define DEBUG_INTERPOLATION TRUE

#define EFI_FSIO TRUE

#define EFI_TEXT_LOGGING TRUE

#define EFI_HISTOGRAMS FALSE

#define CONSOLE_MAX_ACTIONS 128

#define EFI_CLI_SUPPORT FALSE

#define EFI_SIGNAL_EXECUTOR_ONE_TIMER FALSE
#define EFI_SIGNAL_EXECUTOR_SLEEP FALSE

#define EFI_SHAFT_POSITION_INPUT TRUE
#define EFI_ENGINE_CONTROL TRUE

#define EFI_ANALOG_SENSORS TRUE

#define EFI_BOARD_TEST FALSE
#define EFI_JOYSTICK FALSE

#define EFI_MAP_AVERAGING TRUE

#define EFI_FUEL_PUMP TRUE

#define EFI_LUA TRUE

#define EFI_HPFP TRUE
