/**
 * @file efifeatures.h
 *
 * @date Mar 7, 2014
 * @author Andrey Belomutskiy, (c) 2012-2017
 */

#ifndef EFIFEATURES_H_
#define EFIFEATURES_H_

#define EFI_ENABLE_ASSERTS TRUE

#define SPARK_EXTREME_LOGGING TRUE

#define EFI_GPIO_HARDWARE FALSE

#define FUEL_MATH_EXTREME_LOGGING FALSE

#define EFI_DEFAILED_LOGGING FALSE

#define DEBUG_INTERPOLATION TRUE

#define EFI_UNIT_TEST TRUE

#define EFI_FSIO TRUE

#define EFI_HISTOGRAMS FALSE

#define CONSOLE_MAX_ACTIONS 128

#define EFI_CLI_SUPPORT FALSE

#define EFI_SUPPORT_FORD_ASPIRE TRUE
#define EFI_SUPPORT_DODGE_NEON TRUE
#define EFI_SUPPORT_1995_FORD_INLINE_6 TRUE
#define EFI_SUPPORT_FORD_FIESTA TRUE
#define EFI_SUPPORT_NISSAN_PRIMERA TRUE

#define EFI_SIGNAL_EXECUTOR_ONE_TIMER TRUE
#define EFI_SIGNAL_EXECUTOR_SLEEP FALSE

#define EFI_SHAFT_POSITION_INPUT TRUE
#define EFI_ENGINE_CONTROL TRUE

#define EFI_ANALOG_SENSORS TRUE

#endif /* EFIFEATURES_H_ */
