//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi121/connectors/uaefi121.yaml
#pragma once

#define PIN_On-board MAP EFI_ADC_11
#define PIN_8a B8
#define PIN_9a E2
#define PIN_10a E3
#define PIN_11a E4
#define PIN_12a E5
#define PIN_13a C13
#define PIN_14a D15
#define PIN_15a D12
#define PIN_16a D13
#define PIN_17a E0
#define PIN_19a E1
#define PIN_33a D1
#define PIN_34a E14
#define PIN_35a E13
#define PIN_36a E12
#define PIN_37a EFI_ADC_10
#define PIN_38a EFI_ADC_4
#define PIN_39a EFI_ADC_8
#define PIN_40a EFI_ADC_0
#define PIN_41a EFI_ADC_1
#define PIN_42a E11
#define PIN_43a D7
#define PIN_44a D0
#define PIN_45a A9
#define PIN_46a D11
#define PIN_47a D10
#define PIN_48a D2
#define PIN_49a A8
#define PIN_50a B12
#define PIN_51a D3
#define PIN_63a EFI_ADC_13
#define PIN_65a EFI_ADC_12
#define PIN_84a B1
#define PIN_85a A6
#define PIN_86a B9
#define PIN_87a E6
#define PIN_88a C6
#define PIN_89a E15
#define PIN_90a EFI_ADC_3
#define PIN_91a EFI_ADC_14
#define PIN_108a EFI_ADC_5
