# List of all the board related files.
BOARDCPPSRC =  $(PROJECT_DIR)/config/boards/BB_V3/board_configuration.cpp \
				$(PROJECT_DIR)/config/boards/proteus/adc_hack.cpp

BOARDINC = $(PROJECT_DIR)/config/boards/BB_V3

# Override DEFAULT_ENGINE_TYPE
DDEFS += -DSTM32F407xx
DDEFS += -DSHORT_BOARD_NAME=BB_V3 -DDEFAULT_ENGINE_TYPE=MINIMAL_PINS
DDEFS += -DFIRMWARE_ID=\"BB_V3\"
DDEFS += -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::Unassigned
DDEFS += -DHAL_TRIGGER_USE_PAL=TRUE
DDEFS += -DHAL_VSS_USE_PAL=TRUE

DDEFS += -DSTM32_ADC_USE_ADC3=TRUE
DDEFS += -DEFI_SOFTWARE_KNOCK=TRUE

# Hardware serial port on UART 2 -> PD5/PD6 LUB PC10/PC11
EFI_CONSOLE_TTL_PINS = -DEFI_CONSOLE_TX_BRAIN_PIN=Gpio::C10 -DEFI_CONSOLE_RX_BRAIN_PIN=Gpio::C11
