// auto-generated by PinoutLogic.java

#include "pch.h"

const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case EFI_ADC_1: return "Analog 3L";
		case EFI_ADC_0: return "Analog 3O";
		case EFI_ADC_4: return "Analog 3I";
		case EFI_ADC_3: return "Analog 3J";
		case EFI_ADC_2: return "Analog 3M";
		case GPIOE_8: return "Coil 1L";
		case GPIOD_9: return "Coil 1P";
		case GPIOC_9: return "Coil 1F";
		case GPIOD_8: return "Coil 1O";
		case GPIOD_7: return "Injector 2N";
		case GPIOE_6: return "Injector 2P";
		case GPIOB_9: return "Injector 3W";
		case GPIOC_7: return "Coil 1H";
		case GPIOE_5: return "Injector 2O";
		case GPIOB_8: return "Injector 3Y";
		case GPIOE_4: return "Injector 3T";
		case GPIOD_5: return "Injector 3X";
		case GPIOB_7: return "Injector 3Z";
		case GPIOE_3: return "Injector 3S";
		case GPIOD_3: return "Injector 3U";
		case GPIOE_2: return "Injector 3V";
		case GPIOE_10: return "Coil 1I";
		case GPIOE_12: return "Coil 1M";
		case GPIOE_14: return "Coil 1G";
		case GPIOC_13: return "Injector 2M";
		case EFI_ADC_11: return "Analog 3P";
		case EFI_ADC_12: return "Analog 3Q";
		case EFI_ADC_13: return "Analog 3N";
		case EFI_ADC_14: return "Analog VBatt";
		case EFI_ADC_15: return "Analog 3E";
		case EFI_ADC_7: return "Analog 3G";
		case EFI_ADC_6: return "Analog 3H";
	}
	return nullptr;
}
