//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/super-uaefi/connectors/26pin_4k.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/super-uaefi/connectors/60pin.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/super-uaefi/connectors/C-34pins-4k.yaml
#pragma once

#define PIN_11D MM100_UART8_TX
#define PIN_13D MM100_UART8_RX
#define PIN_20D MM100_LED2_GREEN
#define PIN_24D MM100_IN_CRANK
#define PIN_25D MM100_IN_CAM
#define PIN_26D MM100_IN_D4
#define PIN_5A MM100_IN_TPS_ANALOG
#define PIN_6A MM100_IN_O2S2_ANALOG
#define PIN_7A MM100_IN_AUX2_ANALOG
#define PIN_8A MM100_IN_D1
#define PIN_9A MM100_IN_D3
#define PIN_11A MM100_IN_CLT_ANALOG
#define PIN_12A MM100_IN_IAT_ANALOG
#define PIN_13A MM100_IN_PPS_ANALOG
#define PIN_14A MM100_IN_O2S_ANALOG
#define PIN_15A MM100_IN_AUX1_ANALOG
#define PIN_16A MM100_MEGA_UAEFI_IN_AUX3
#define PIN_17A MM100_IN_D2
#define PIN_2B MM100_IGN1
#define PIN_3B MM100_IGN2
#define PIN_4B MM100_IGN3
#define PIN_5B MM100_IGN4
#define PIN_6B MM100_IGN5
#define PIN_7B MM100_IGN6
#define PIN_8B MM100_INJ6
#define PIN_9B MM100_INJ5
#define PIN_10B MM100_INJ4
#define PIN_11B MM100_INJ3
#define PIN_12B MM100_INJ2
#define PIN_13B MM100_MEGA_UAEFI_INJ1
#define PIN_18B MM100_MEGA_UAEFI_SPI2_SCK
#define PIN_19B MM100_SPI2_CS
#define PIN_20B MM100_INJ7
#define PIN_21B MM100_INJ8
#define PIN_22B MM100_OUT_PWM1
#define PIN_25B MM100_IN_VSS
#define PIN_26B MM100_IN_MAP1_ANALOG
#define PIN_1C MM100_IN_VBATT
#define PIN_29C MM100_IGN8
#define PIN_30C MM100_IGN7
#define PIN_31C MM100_OUT_PWM2
