//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen154hyundai/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A6: return "Cam - K62 rev B";
		case Gpio::A7: return "Cam - K15";
		case Gpio::A9: return "Aux P67";
		case Gpio::B1: return "Crank - K17 rev B";
		case Gpio::C13: return "Coil 1";
		case Gpio::D10: return "INJ_4 k28";
		case Gpio::D11: return "INJ_3 k27";
		case Gpio::D12: return "MIL";
		case Gpio::D15: return "Tacho";
		case Gpio::D3: return "Aux P66";
		case Gpio::D9: return "VVT1";
		case Gpio::E3: return "Coil 4";
		case Gpio::E4: return "Coil 3";
		case Gpio::E5: return "Coil 2";
		case Gpio::F10: return "A43 Clutch Input";
		case Gpio::F11: return "K40 VSS";
		case Gpio::F12: return "VVT2";
		case Gpio::F13: return "K47 BK1 Wastegate Solenoid";
		case Gpio::F14: return "K48 LS1";
		case Gpio::F4: return "Crank - K17 rev C";
		case Gpio::F5: return "Cam - K62 rev C";
		case Gpio::F8: return "A29 Brake Input";
		case Gpio::F9: return "A57 AC Request";
		case Gpio::G12: return "K87 AC Relay";
		case Gpio::G13: return "Fuel Pump K70";
		case Gpio::G14: return "Main Relay K64";
		case Gpio::G3: return "Fan Relay Low";
		case Gpio::G4: return "Fan Relay HI";
		case Gpio::G5: return "Aux P68";
		case Gpio::G7: return "INJ_1 k25";
		case Gpio::G8: return "INJ_2 k26";
		default: return nullptr;
	}
	return nullptr;
}
