//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen121nissan/connectors/121nissanAUX.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen121nissan/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D9,
	Gpio::D11,
	Gpio::G7,
	Gpio::F12,
	Gpio::D10,
	Gpio::G8,
	Gpio::G5,
	Gpio::G14,
	Gpio::D12,
	Gpio::C8,
	Gpio::C7,
	Gpio::C6,
	Gpio::F13,
	Gpio::F14,
	Gpio::D3,
	Gpio::E2,
	Gpio::E4,
	Gpio::C13,
	Gpio::B8,
	Gpio::E3,
	Gpio::E5,
}
