//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen121nissan/connectors/121nissanAUX.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen121nissan/connectors/main.yaml
#pragma once

#define PIN_aux2 H144_OUT_PWM4
#define PIN_aux3 H144_OUT_PWM3
#define PIN_aux4 F6
#define PIN_auxP65 H144_IN_RES3
#define PIN_aux7 F4
#define PIN_aux8 C6
#define PIN_aux9 F3
#define PIN_10a F13
#define PIN_11a F14
#define PIN_13a_event_inputs B1
#define PIN_14a_event_inputs A6
#define PIN_21a D9
#define PIN_22a D11
#define PIN_23a G7
#define PIN_29a D3
#define PIN_33a A7
#define PIN_34a EFI_ADC_13
#define PIN_40a F12
#define PIN_41a D10
#define PIN_42a G8
#define PIN_50a EFI_ADC_4
#define PIN_51a_broken1 EFI_ADC_0
#define PIN_60a E2
#define PIN_61a E4
#define PIN_62a C13
#define PIN_69a EFI_ADC_8
#define PIN_P66 EFI_ADC_10
#define PIN_P67 EFI_ADC_11
#define PIN_P68 EFI_ADC_2
#define PIN_73a EFI_ADC_12
#define PIN_79a B8
#define PIN_80a E3
#define PIN_81a E5
#define PIN_98a EFI_ADC_14
#define PIN_101a F9
#define PIN_102a F10
#define PIN_104a G5
#define PIN_106a EFI_ADC_3
#define PIN_109a EFI_ADC_5
#define PIN_111a G14
#define PIN_113a D12
