//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-gold/connectors/34pins-3k-A.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-gold/connectors/34pins-4k-B.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::H144_IGN_4, // 10A Coil 4
	Gpio::H144_IGN_3, // 11A Coil 3
	Gpio::H144_IGN_2, // 12A Coil 2
	Gpio::H144_IGN_1, // 13A Coil 1
// "10A Coil 4",
// "11A Coil 3",
// "12A Coil 2",
// "13A Coil 1",
}
