//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellenNA8_96/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D12, // 1A - ECF
	Gpio::G4, // 1E - Check Engine Light
	Gpio::G11, // 1G - AC Relay
	Gpio::G2, // 1U - Fuel Pump
	Gpio::D13, // 3L - TACH
	Gpio::D14, // 3Q - IDLE
	Gpio::G7, // 3U - INJ_1
	Gpio::G8, // 3V - INJ_2
	Gpio::D11, // 3W - INJ_3
	Gpio::D10, // 3X - INJ_4
	Gpio::G13, // 3Z - O2H2
	Gpio::F12, // 4D - BOOST OUT
	Gpio::D9, // 4E - VVT
	Gpio::D2, // P18/P22
	Gpio::A9, // 1B - AC Fan Relay
	Gpio::C13, // 3N - IGN_1 (1&4)
	Gpio::E5, // 3R - IGN_2 (2&3)
	Gpio::C7, // ETB +
	Gpio::C8, // ETB -
	Gpio::C6, // ETB EN
}
