//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen-nb1/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::A1: return "TPS1";
		case Gpio::A3: return "PPS1";
		case Gpio::A6: return "2H - CAM";
		case Gpio::A7: return "3S - EGR BOOST IN";
		case Gpio::A9: return "1I AC Fan Relay";
		case Gpio::B0: return "2A - Pressure Input";
		case Gpio::B1: return "2J - CRANK";
		case Gpio::C1: return "3D - MAP";
		case Gpio::C13: return "3G - IGN_1 (1&4)";
		case Gpio::C4: return "4C - IN TEMP/PPS2";
		case Gpio::C5: return "1P - AC Switch";
		case Gpio::C6: return "ETB EN";
		case Gpio::C7: return "ETB +";
		case Gpio::C8: return "ETB -";
		case Gpio::D10: return "3Z - INJ_4";
		case Gpio::D11: return "3Y - INJ_3";
		case Gpio::D12: return "1R - ECF";
		case Gpio::D13: return "2K - TACH";
		case Gpio::D14: return "2Q - IDLE";
		case Gpio::D15: return "1O - ALTERN";
		case Gpio::D3: return "1U - O2H";
		case Gpio::D9: return "4E - VVT";
		case Gpio::E12: return "4B - DIGITAL/FLEX";
		case Gpio::E13: return "3I - Clutch";
		case Gpio::E14: return "1V - Neutral";
		case Gpio::E5: return "3H - IGN_2 (2&3)";
		case Gpio::F10: return "1G - Steering/RES2";
		case Gpio::F11: return "2D - VSS";
		case Gpio::F12: return "3T/4D - BOOST OUT";
		case Gpio::F14: return "3Q - VICS";
		case Gpio::F3: return "3J - O2S2";
		case Gpio::F9: return "1F - Brake/RES1";
		case Gpio::G11: return "1S - AC Relay";
		case Gpio::G12: return "1Q - Aternator Warning Lamp";
		case Gpio::G13: return "3V - O2H2";
		case Gpio::G2: return "2M US / 2P EUROPE - FPUMP";
		case Gpio::G4: return "1E - Check Engine Light";
		case Gpio::G7: return "3W - INJ_1";
		case Gpio::G8: return "3X - INJ_2";
		default: return nullptr;
	}
	return nullptr;
}
