//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-4chan/connectors/alphax-4chan-aux.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-4chan/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::H144_LS_5,
	Gpio::H144_LS_6,
	Gpio::H144_OUT_IO12,
	Gpio::H144_LS_1,
	Gpio::H144_LS_2,
	Gpio::H144_OUT_IO11,
	Gpio::H144_OUT_PWM1,
	Gpio::H144_LS_3,
	Gpio::H144_LS_4,
	Gpio::H144_OUT_PWM5,
	Gpio::H144_IGN_7,
	Gpio::H144_IGN_8,
	Gpio::H144_OUT_IO10,
	Gpio::H144_IGN_5,
	Gpio::H144_IGN_6,
	Gpio::H144_OUT_PWM7,
	Gpio::H144_OUT_PWM8,
	Gpio::H144_OUT_IO13,
	Gpio::H144_GP3,
	Gpio::H144_IGN_1,
	Gpio::H144_IGN_2,
	Gpio::H144_OUT_PWM3,
	Gpio::H144_IGN_3,
	Gpio::H144_IGN_4,
	Gpio::H144_OUT_IO6,
}
