//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/microrusefi/connectors/J4.yaml
// auto-generated by PinoutLogic.java based on config/boards/microrusefi/connectors/iobox.yaml
// auto-generated by PinoutLogic.java based on config/boards/microrusefi/connectors/main.yaml
// auto-generated by PinoutLogic.java based on config/boards/microrusefi/connectors/pads.yaml
#pragma once

#define PIN_3 B8
#define PIN_6 B9
#define PIN_10 C12
#define PIN_7 A15
#define PIN_canbus_1 MSIOBOX_0_OUT_1
#define PIN_canbus_2 MSIOBOX_0_OUT_2
#define PIN_canbus_3 MSIOBOX_0_OUT_3
#define PIN_canbus_4 MSIOBOX_0_OUT_4
#define PIN_16 MSIOBOX_0_OUT_5
#define PIN_17 MSIOBOX_0_OUT_6
#define PIN_35 MSIOBOX_0_OUT_7
#define PIN_32_event_inputs MSIOBOX_0_VSS_1
#define PIN_32_switch_inputs MSIOBOX_0_VSS_1
#define PIN_4_event_inputs MSIOBOX_0_VSS_2
#define PIN_4_switch_inputs MSIOBOX_0_VSS_2
#define PIN_11_event_inputs MSIOBOX_0_VSS_3
#define PIN_11_switch_inputs MSIOBOX_0_VSS_3
#define PIN_12_event_inputs MSIOBOX_0_VSS_4
#define PIN_12_switch_inputs MSIOBOX_0_VSS_4
#define PIN_6 MSIOBOX_0_SW_1
#define PIN_1 EFI_ADC_11
#define PIN_3 TLE8888_PIN_5
#define PIN_7 TLE8888_PIN_6
#define PIN_9 D4
#define PIN_10 D3
#define PIN_11 D2
#define PIN_12 D1
#define PIN_13 D6
#define PIN_14 D7
#define PIN_18_switch_inputs A0
#define PIN_18_analog_inputs EFI_ADC_0
#define PIN_19_switch_inputs C2
#define PIN_19_analog_inputs EFI_ADC_12
#define PIN_20_switch_inputs C3
#define PIN_20_analog_inputs EFI_ADC_13
#define PIN_22_event_inputs A3
#define PIN_22_switch_inputs A3
#define PIN_22_analog_inputs EFI_ADC_3
#define PIN_23_event_inputs A1
#define PIN_23_switch_inputs A1
#define PIN_23_analog_inputs EFI_ADC_1
#define PIN_23_sent_inputs A1
#define PIN_24_event_inputs A2
#define PIN_24_switch_inputs A2
#define PIN_24_analog_inputs EFI_ADC_2
#define PIN_25_event_inputs A5
#define PIN_25_switch_inputs A5
#define PIN_26_switch_inputs A6
#define PIN_26_analog_inputs EFI_ADC_6
#define PIN_27_switch_inputs C0
#define PIN_27_analog_inputs EFI_ADC_10
#define PIN_28_outputs A4
#define PIN_28_switch_inputs A4
#define PIN_28_analog_inputs EFI_ADC_4
#define PIN_30_switch_inputs C5
#define PIN_30_analog_inputs EFI_ADC_15
#define PIN_31_switch_inputs A7
#define PIN_31_analog_inputs EFI_ADC_7
#define PIN_32_outputs C4
#define PIN_32_switch_inputs C4
#define PIN_32_analog_inputs EFI_ADC_14
#define PIN_33 TLE8888_PIN_23
#define PIN_34 TLE8888_PIN_22
#define PIN_35 TLE8888_PIN_21
#define PIN_36_outputs B0
#define PIN_36_switch_inputs B0
#define PIN_36_analog_inputs EFI_ADC_8
#define PIN_37 TLE8888_PIN_1
#define PIN_38 TLE8888_PIN_2
#define PIN_40_outputs B1
#define PIN_40_switch_inputs B1
#define PIN_40_analog_inputs EFI_ADC_9
#define PIN_41 TLE8888_PIN_3
#define PIN_42 TLE8888_PIN_4
#define PIN_43 TLE8888_PIN_24
#define PIN_45 C6
#define PIN_J10 E6
#define PIN_J11 E5
#define PIN_J18 B7
