/**
 * @file    chibios_pdl_vectors.h
 * @brief   Core IRQ vector mappings
 * @author  andreika <prometheus.pcb@gmail.com>
 */

#ifndef __CHIBIOS_PDL_VECTORS_H__
#define __CHIBIOS_PDL_VECTORS_H__

// generated from startup_s6e2c5.S + ChibiOS/os/common/startup/ARMCMx/compilers/GCC/vectors.S
#define CSV_IRQHandler Vector40
#define SWDT_IRQHandler Vector44
#define LVD_IRQHandler Vector48
#define IRQ003SEL_IRQHandler Vector4C
#define IRQ004SEL_IRQHandler Vector50
#define IRQ005SEL_IRQHandler Vector54
#define IRQ006SEL_IRQHandler Vector58
#define IRQ007SEL_IRQHandler Vector5C
#define IRQ008SEL_IRQHandler Vector60
#define IRQ009SEL_IRQHandler Vector64
#define IRQ010SEL_IRQHandler Vector68
#define EXINT0_IRQHandler Vector6C
#define EXINT1_IRQHandler Vector70
#define EXINT2_IRQHandler Vector74
#define EXINT3_IRQHandler Vector78
#define EXINT4_IRQHandler Vector7C
#define EXINT5_IRQHandler Vector80
#define EXINT6_IRQHandler Vector84
#define EXINT7_IRQHandler Vector88
#define QPRC0_IRQHandler Vector8C
#define QPRC1_IRQHandler Vector90
#define MFT0_WFG_DTIF_IRQHandler Vector94
#define MFT1_WFG_DTIF_IRQHandler Vector98
#define MFT2_WFG_DTIF_IRQHandler Vector9C
#define MFT0_FRT_PEAK_IRQHandler VectorA0
#define MFT0_FRT_ZERO_IRQHandler VectorA4
#define MFT0_ICU_IRQHandler VectorA8
#define MFT0_OCU_IRQHandler VectorAC
#define MFT1_FRT_PEAK_IRQHandler VectorB0
#define MFT1_FRT_ZERO_IRQHandler VectorB4
#define MFT1_ICU_IRQHandler VectorB8
#define MFT1_OCU_IRQHandler VectorBC
#define MFT2_FRT_PEAK_IRQHandler VectorC0
#define MFT2_FRT_ZERO_IRQHandler VectorC4
#define MFT2_ICU_IRQHandler VectorC8
#define MFT2_OCU_IRQHandler VectorCC
#define PPG00_02_04_IRQHandler VectorD0
#define PPG08_10_12_IRQHandler VectorD4
#define PPG16_18_20_IRQHandler VectorD8
#define BT0_IRQHandler VectorDC
#define BT1_IRQHandler VectorE0
#define BT2_IRQHandler VectorE4
#define BT3_IRQHandler VectorE8
#define BT4_IRQHandler VectorEC
#define BT5_IRQHandler VectorF0
#define BT6_IRQHandler VectorF4
#define BT7_IRQHandler VectorF8
#define DT_IRQHandler VectorFC
#define WC_IRQHandler Vector100
#define EXTBUS_ERR_IRQHandler Vector104
#define RTC_IRQHandler Vector108
#define EXINT8_IRQHandler Vector10C
#define EXINT9_IRQHandler Vector110
#define EXINT10_IRQHandler Vector114
#define EXINT11_IRQHandler Vector118
#define EXINT12_IRQHandler Vector11C
#define EXINT13_IRQHandler Vector120
#define EXINT14_IRQHandler Vector124
#define EXINT15_IRQHandler Vector128
#define TIM_IRQHandler Vector12C
#define MFS0_RX_IRQHandler Vector130
#define MFS0_TX_IRQHandler Vector134
#define MFS1_RX_IRQHandler Vector138
#define MFS1_TX_IRQHandler Vector13C
#define MFS2_RX_IRQHandler Vector140
#define MFS2_TX_IRQHandler Vector144
#define MFS3_RX_IRQHandler Vector148
#define MFS3_TX_IRQHandler Vector14C
#define MFS4_RX_IRQHandler Vector150
#define MFS4_TX_IRQHandler Vector154
#define MFS5_RX_IRQHandler Vector158
#define MFS5_TX_IRQHandler Vector15C
#define MFS6_RX_IRQHandler Vector160
#define MFS6_TX_IRQHandler Vector164
#define MFS7_RX_IRQHandler Vector168
#define MFS7_TX_IRQHandler Vector16C
#define ADC0_IRQHandler Vector170
#define ADC1_IRQHandler Vector174
#define USB0_F_IRQHandler Vector178
#define USB0_H_F_IRQHandler Vector17C
#define CAN0_IRQHandler Vector180
#define CAN1_CANFD0_IRQHandler Vector184
//#define Default_Handler Vector188
#define DMAC0_IRQHandler Vector18C
#define DMAC1_IRQHandler Vector190
#define DMAC2_IRQHandler Vector194
#define DMAC3_IRQHandler Vector198
#define DMAC4_IRQHandler Vector19C
#define DMAC5_IRQHandler Vector1A0
#define DMAC6_IRQHandler Vector1A4
#define DMAC7_IRQHandler Vector1A8
#define DSTC_IRQHandler Vector1AC
#define EXINT16_19_IRQHandler Vector1B0
#define EXINT20_23_IRQHandler Vector1B4
#define EXINT24_27_IRQHandler Vector1B8
#define EXINT28_31_IRQHandler Vector1BC
#define QPRC2_IRQHandler Vector1C0
#define QPRC3_IRQHandler Vector1C4
#define BT8_IRQHandler Vector1C8
#define BT9_IRQHandler Vector1CC
#define BT10_IRQHandler Vector1D0
#define BT11_IRQHandler Vector1D4
#define BT12_15_IRQHandler Vector1D8
#define MFS8_RX_IRQHandler Vector1DC
#define MFS8_TX_IRQHandler Vector1E0
#define MFS9_RX_IRQHandler Vector1E4
#define MFS9_TX_IRQHandler Vector1E8
#define MFS10_RX_IRQHandler Vector1EC
#define MFS10_TX_IRQHandler Vector1F0
#define MFS11_RX_IRQHandler Vector1F4
#define MFS11_TX_IRQHandler Vector1F8
#define ADC2_IRQHandler Vector1FC
#define DSTC_HW_IRQHandler Vector200
#define USB1_F_IRQHandler Vector204
#define USB1_H_F_IRQHandler Vector208
#define HSSPI_IRQHandler Vector20C
//#define Default_Handler Vector210
#define PCRC_I2S0_1_IRQHandler Vector214
#define SD_IRQHandler Vector218
#define FLASHIF_IRQHandler Vector21C
#define MFS12_RX_IRQHandler Vector220
#define MFS12_TX_IRQHandler Vector224
#define MFS13_RX_IRQHandler Vector228
#define MFS13_TX_IRQHandler Vector22C
#define MFS14_RX_IRQHandler Vector230
#define MFS14_TX_IRQHandler Vector234
#define MFS15_RX_IRQHandler Vector238
#define MFS15_TX_IRQHandler Vector23C

#endif // of __CHIBIOS_PDL_VECTORS_H__
