//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen154hyundai_f7/connectors/154hyundaiAUX.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen154hyundai_f7/connectors/main.yaml
#pragma once

#define PIN_X2 H144_OUT_IO2
#define PIN_wg_pwm H144_OUT_PWM4
#define PIN_wg_dir H144_OUT_PWM5
#define PIN_wg_dis H144_OUT_IO13
#define PIN_X3 D14
#define PIN_X4_event_inputs H144_IN_SENS4
#define PIN_X4_switch_inputs H144_IN_SENS4
#define PIN_X7_event_inputs H144_IN_SENS3
#define PIN_X7_switch_inputs H144_IN_SENS3
#define PIN_X8 H144_OUT_IO1
#define PIN_X9_event_inputs H144_IN_SENS2
#define PIN_X9_switch_inputs H144_IN_SENS2
#define PIN_X10 EFI_ADC_6
#define PIN_X11 EFI_ADC_9
#define PIN_K2 H144_IN_VBATT
#define PIN_K10 H144_IN_MAP2
#define PIN_K15 H144_IN_D_3
#define PIN_K17 H144_IN_D_1
#define PIN_K21 H144_IN_AT1
#define PIN_K22 H144_IN_AUX3_ANALOG
#define PIN_K25 MC33810_0_OUT_0
#define PIN_K26 MC33810_0_OUT_1
#define PIN_K27 MC33810_0_OUT_2
#define PIN_K28 MC33810_0_OUT_3
#define PIN_K31 H144_IN_MAP1
#define PIN_K32 H144_IN_TPS2
#define PIN_K33 H144_IN_CLT
#define PIN_K35 H144_IN_PPS2
#define PIN_K40 H144_IN_D_4
#define PIN_K47 H144_LS_7
#define PIN_K48 H144_LS_8
#define PIN_K53 H144_IN_IAT
#define PIN_K54 H144_IN_MAP3
#define PIN_K58 H144_IN_AT2
#define PIN_K62 H144_IN_D_2
#define PIN_K64 H144_OUT_IO3
#define PIN_K65 H144_OUT_IO7
#define PIN_K66 H144_LS_5
#define PIN_K68 H144_LS_6
#define PIN_K70 H144_OUT_IO9
#define PIN_K80 H144_IN_TPS
#define PIN_K82 H144_IN_PPS
#define PIN_K86 H144_OUT_PWM7
#define PIN_K87 H144_OUT_IO10
#define PIN_K88 H144_OUT_IO8
#define PIN_K92 H144_OUT_PWM8
#define PIN_A1 MC33810_0_GD_3
#define PIN_A16 MC33810_0_GD_1
#define PIN_A29 H144_IN_RES3
#define PIN_A31 MC33810_0_GD_0
#define PIN_A43 H144_IN_RES2
#define PIN_A46 MC33810_0_GD_2
#define PIN_A57 H144_IN_RES1
