//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen154hyundai_f7/connectors/154hyundaiAUX.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen154hyundai_f7/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::H144_OUT_IO2, // X2 AuxLS3
	Gpio::H144_OUT_PWM4, // wg_pwm
	Gpio::H144_OUT_PWM5, // wg_dir
	Gpio::H144_OUT_IO13, // wg_dis
	Gpio::D14, // X3 AuxLS2
	Gpio::H144_OUT_IO1, // X8 AuxLS1
	Gpio::MC33810_0_OUT_0, // INJ_1 k25
	Gpio::MC33810_0_OUT_1, // INJ_2 k26
	Gpio::MC33810_0_OUT_2, // INJ_3 k27
	Gpio::MC33810_0_OUT_3, // INJ_4 k28
	Gpio::H144_OUT_IO3, // Main Relay K64
	Gpio::H144_OUT_IO9, // Fuel Pump K70
	Gpio::H144_OUT_IO10, // K87 AC Relay
	Gpio::H144_OUT_PWM8, // MIL
	Gpio::H144_LS_7, // K47 BK1 Wastegate Solenoid
	Gpio::H144_LS_8, // K48 OUT_RCV
	Gpio::H144_OUT_IO7, // Fan Relay Low
	Gpio::H144_LS_5, // VVT1
	Gpio::H144_LS_6, // VVT2
	Gpio::H144_OUT_PWM7, // Tacho
	Gpio::H144_OUT_IO8, // Fan Relay HI
	Gpio::MC33810_0_GD_3, // Coil 4
	Gpio::MC33810_0_GD_1, // Coil 2
	Gpio::MC33810_0_GD_0, // Coil 1
	Gpio::MC33810_0_GD_2, // Coil 3
// "X2 AuxLS3",
// "wg_pwm",
// "wg_dir",
// "wg_dis",
// "X3 AuxLS2",
// "X8 AuxLS1",
// "INJ_1 k25",
// "INJ_2 k26",
// "INJ_3 k27",
// "INJ_4 k28",
// "Main Relay K64",
// "Fuel Pump K70",
// "K87 AC Relay",
// "MIL",
// "K47 BK1 Wastegate Solenoid",
// "K48 OUT_RCV",
// "Fan Relay Low",
// "VVT1",
// "VVT2",
// "Tacho",
// "Fan Relay HI",
// "Coil 4",
// "Coil 2",
// "Coil 1",
// "Coil 3",
}
