#!/usr/bin/env bash

export EXTRA_PARAMS="\
-DEFI_SOFTWARE_KNOCK=FALSE \
-DHAL_TRIGGER_USE_ADC=TRUE \
-DSTM32_ADC_USE_ADC3=TRUE \
"

export PROJECT_BOARD="hellen88bmw"
export PROJECT_CPU="ARCH_STM32F4"
export SHORT_BOARD_NAME=hellen88bmw
