package com.rusefi.enums;
// based on ./console/binary/generated/live_data_ids.h
//auto-generated by ToJavaEnum.java



public enum live_data_e {
	LDS_output_channels,
	LDS_fuel_computer,
	LDS_ignition_state,
	LDS_knock_controller,
	LDS_high_pressure_fuel_pump,
	LDS_injector_model,
	LDS_launch_control_state,
	LDS_antilag_system_state,
	LDS_boost_control,
	LDS_ac_control,
	LDS_fan_control,
	LDS_fuel_pump_control,
	LDS_main_relay,
	LDS_engine_state,
	LDS_tps_accel_state,
	LDS_trigger_central,
	LDS_trigger_state,
	LDS_trigger_state_primary,
	LDS_wall_fuel_state,
	LDS_idle_state,
	LDS_electronic_throttle,
	LDS_wideband_state,
	LDS_dc_motors,
	LDS_sent_state,
	LDS_throttle_model,
	LDS_vvt,
	LDS_lambda_monitor,
}
