package com.rusefi.enums;
// based on ./controllers/algo/engine_types.h
//auto-generated by ToJavaEnum.java



public enum ts_14_command {
	TS_14_0,
	TS_14_1,
	TS_GRAB_TPS_CLOSED,
	TS_GRAB_TPS_WOT,
	TS_14_4,
	TS_14_5,
	TS_GRAB_PEDAL_UP,
	TS_GRAB_PEDAL_WOT,
	TS_RESET_TLE8888,
	TS_14_9,
	TS_WRITE_FLASH,
	TS_ETB_RESET,
}
