#define TRIGGER_SCOPE_ADC ADCD3

#define TRIGGER_SCOPE_SAMPLE_TIME ADC_SAMPLE_144

#define TRIGGER_SCOPE_PIN_CH1 Gpio::F10
#define TRIGGER_SCOPE_ADC_CH1 ADC_CHANNEL_IN8

#define TRIGGER_SCOPE_PIN_CH2 Gpio::F8
#define TRIGGER_SCOPE_ADC_CH2 ADC_CHANNEL_IN6
