//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/B.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/C.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/D.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/E.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/iobox.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/uaefi-A.yaml
#pragma once

#define PIN_B1 A8
#define PIN_C3 EFI_ADC_1
#define PIN_C5 E12
#define PIN_C9 E15
