//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/B.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/C.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/D.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/E.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/iobox.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/uaefi/connectors/uaefi-A.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::MM100_INJ6, // B1 injector output 6
	Gpio::MM100_INJ5, // B2 injector output 5
	Gpio::MM100_INJ4, // B3 injector output 4
	Gpio::MM100_INJ3, // B4 injector output 3
	Gpio::MM100_INJ2, // B5 injector output 2
	Gpio::MM100_INJ1, // B6 injector output 1
	Gpio::MM100_INJ7, // B7 VVT1 or Low Side output 1 (has flyback D2)
	Gpio::MM100_IGN8, // B8 Fan Relay Weak Low Side output 2 (no flyback here)
	Gpio::MM100_IGN7, // B9 Main Relay Weak Low Side output 1 (no flyback here)
	Gpio::MM100_OUT_PWM2, // B16 Low Side output 4 / Fuel Pump Relay (has flyback D5)
	Gpio::MM100_OUT_PWM1, // B17 Low Side output 3 or injector 7 (has flyback D4)
	Gpio::MM100_INJ8, // B18 VVT2 or Idle or Low Side output 2 or injector 8 (has flyback D3)
	Gpio::MM100_IGN6, // B10 Coil 6
	Gpio::MM100_IGN4, // B11 Coil 4
	Gpio::MM100_IGN3, // B12 Coil 3
	Gpio::MM100_IGN5, // B13 Coil 5
	Gpio::MM100_IGN2, // B14 Coil 2
	Gpio::MM100_IGN1, // B15 Coil 1
	Gpio::MSIOBOX_0_OUT_1, // MS IO-Box 0 OUT 1
	Gpio::MSIOBOX_0_OUT_2, // MS IO-Box 0 OUT 2
	Gpio::MSIOBOX_0_OUT_3, // MS IO-Box 0 OUT 3
	Gpio::MSIOBOX_0_OUT_4, // MS IO-Box 0 OUT 4
// "B1 injector output 6",
// "B2 injector output 5",
// "B3 injector output 4",
// "B4 injector output 3",
// "B5 injector output 2",
// "B6 injector output 1",
// "B7 VVT1 or Low Side output 1 (has flyback D2)",
// "B8 Fan Relay Weak Low Side output 2 (no flyback here)",
// "B9 Main Relay Weak Low Side output 1 (no flyback here)",
// "B16 Low Side output 4 / Fuel Pump Relay (has flyback D5)",
// "B17 Low Side output 3 or injector 7 (has flyback D4)",
// "B18 VVT2 or Idle or Low Side output 2 or injector 8 (has flyback D3)",
// "B10 Coil 6",
// "B11 Coil 4",
// "B12 Coil 3",
// "B13 Coil 5",
// "B14 Coil 2",
// "B15 Coil 1",
// "MS IO-Box 0 OUT 1",
// "MS IO-Box 0 OUT 2",
// "MS IO-Box 0 OUT 3",
// "MS IO-Box 0 OUT 4",
}
