#!/bin/bash
export PROJECT_BOARD=f429-discovery
export PROJECT_CPU=ARCH_STM32F4

#-DDUMMY -DEFI_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_ASSERTS=FALSE -DCH_DBG_ENABLE_STACK_CHECK=FALSE -DCH_DBG_FILL_THREADS=FALSE -DCH_DBG_THREADS_PROFILING=FALSE"

bash ../common_make.sh
