BOARDCPPSRC = $(BOARD_DIR)/board_configuration.cpp

DDEFS += -DFIRMWARE_ID=\"t-b-g\"
DDEFS += -DSTATIC_BOARD_ID=STATIC_BOARD_ID_TBG

DDEFS += -DHAL_USE_ADC=FALSE
DDEFS += -DHAL_USE_GPT=FALSE

DDEFS += -DRAM_UNUSED_SIZE=10000