//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-2chan/connectors/alphax-2chan-aux.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-2chan/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::H144_LS_3,
	Gpio::H144_LS_4,
	Gpio::H144_IGN_4,
	Gpio::H144_IGN_3,
	Gpio::H144_OUT_PWM2,
	Gpio::H144_LS_1,
	Gpio::H144_LS_2,
	Gpio::H144_OUT_PWM4,
	Gpio::H144_OUT_PWM1,
	Gpio::H144_OUT_PWM3,
	Gpio::H144_IGN_1,
	Gpio::H144_IGN_2,
}
