//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-2chan/connectors/alphax-2chan-aux.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-2chan/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::H144_LS_3, // Aux2 - Inj 3
	Gpio::H144_LS_4, // Aux4 - Inj 4
	Gpio::H144_IGN_4, // Aux6 - Ign 4
	Gpio::H144_IGN_3, // Aux8 - Ign 3
	Gpio::H144_OUT_PWM2, // A3 - Fuel Pump
	Gpio::H144_LS_1, // A8 - Injector A
	Gpio::H144_LS_2, // B8 - Injector B
	Gpio::H144_OUT_PWM4, // C1 - Fan Relay
	Gpio::H144_OUT_PWM1, // C8 - Idle
	Gpio::H144_OUT_PWM3, // A4 - Tachometer
	Gpio::H144_IGN_1, // A6 - Ignition A
	Gpio::H144_IGN_2, // A7 - Ignition B
}
