//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellenMiataNB1/connectors/main.yaml
#pragma once

#define PIN_1B EFI_ADC_5
#define PIN_1F F9
#define PIN_1E G4
#define PIN_2D F11
