[WueAnalyze]

;						wueCurveName, afrTempCompensationCurve, lambdaTargetTableName, lambdaChannel, coolantTempChannel, egoCorrectionChannel, wueChannel, activeCondition
	wueAnalyzeMap = wueAnalyzer_warmup_curve, wueAfrTargetOffsetCurve, lambdaTableTbl, lambdaValue, coolant, running_coolantTemperatureCoefficient, egoCorrectionForVeAnalyze, { useLambdaOnInterface }
	wueAnalyzeMap = wueAnalyzer_warmup_curve, wueAfrTargetOffsetCurve, afrTableTbl, AFRValue, coolant, running_coolantTemperatureCoefficient, egoCorrectionForVeAnalyze, { !useLambdaOnInterface }
	lambdaTargetTables = lambdaTableTbl, afrTSCustom

	wuePercentOffset = 0 ; for working with 0 based enrichment set to 100
	option = disableLiveUpdates
	option = burnOnSend

;	filter = std_DeadLambda ; Auto build

	filter = decelFilterMap,"After Start Enrich", engine,			&	, 4 ,		, false
	filter = accelFilterTp, "TP Accel Enrich"	, engine,			&	, 16,		, false
	filter = decelFilterTp, "TP Decel Enrich"	, engine,			&	, 32,		, false
	filter = accelFilterMap,"MAP Accel Enrich"  , engine,			&	, 64,		, false
	filter = decelFilterMap,"MAP Decel Enrich"  , engine,			&	, 128,		, false
	; this works, just another way to skin a cat
	;filter = decelFilter, "Decel Flag" , tpsaccden,			>		, 0,		, false
	filter = overrunFilter, "Overrun"	, pulseWidth1,  =		, 0,				, false
	filter = highThrottle, "High Throttle"	, throttle,  >		, 15,			, true
	filter = lowRpm,		"Low RPM"	,		rpm,		<		, 300,		, false
	filter = std_Custom ; Standard Custom Expression Filter.
