package com.rusefi.tracing;

public class EnumNames {
	public static final String[] TypeNames = {
	"INVALID",
	"ISR",
	"ContextSwitch",
	"OutputPinSetValue",
	"DecodeTriggerEvent",
	"EnginePeriodicFastCallback",
	"EnginePeriodicSlowCallback",
	"EngineStatePeriodicFastCallback",
	"HandleShaftSignal",
	"EventQueueInsertTask",
	"EventQueueExecuteAll",
	"SingleTimerExecutorDoExecute",
	"SingleTimerExecutorScheduleTimerCallback",
	"PeriodicControllerPeriodicTask",
	"PeriodicTimerControllerPeriodicTask",
	"AdcCallbackFast",
	"AdcCallbackSlow",
	"AdcConversionSlow",
	"AdcConversionFast",
	"AdcSubscriptionUpdateSubscribers",
	"GetRunningFuel",
	"GetInjectionDuration",
	"HandleFuel",
	"MainTriggerCallback",
	"OnTriggerEventSparkLogic",
	"ShaftPositionListeners",
	"GetBaseFuel",
	"GetTpsEnrichment",
	"GetSpeedDensityFuel",
	"WallFuelAdjust",
	"MapAveragingTriggerCallback",
	"AdcCallbackFastComplete",
	"SingleTimerExecutorScheduleByTimestamp",
	"ScheduleByAngle",
	"EventQueueExecuteCallback",
	"PwmGeneratorCallback",
	"TunerStudioHandleCrcCommand",
	"PwmConfigTogglePwmState",
	"PwmConfigStateChangeCallback",
	};
}
