//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen-112-17/connectors/main.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::E12: return "231 Cam";
		case Gpio::E13: return "232 VSS";
		case Gpio::E6: return "Main Relay";
		default: return nullptr;
	}
	return nullptr;
}
