//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen-112-17/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::MM100_IGN8,
}
