//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen88bmw/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::D9,
	Gpio::F12,
	Gpio::D10,
	Gpio::F13,
	Gpio::D3,
	Gpio::D11,
	Gpio::G8,
	Gpio::G7,
	Gpio::F14,
	Gpio::G14,
	Gpio::D12,
	Gpio::E3,
	Gpio::B8,
	Gpio::E2,
	Gpio::C9,
	Gpio::D15,
	Gpio::C13,
	Gpio::E5,
	Gpio::E4,
}
