//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellen128/connectors/main.yaml
#pragma once

Gpio GENERATED_OUTPUTS[] = {
	Gpio::I1, // P19_OUT_LOW11
	Gpio::I0, // P35_OUT_LOW9
	Gpio::C9, // P33_PWM5
	Gpio::A8, // P18_OUT_PP2
	Gpio::D12, // A6 - Fan Control
	Gpio::H14, // C21 - Evap Purge Control
	Gpio::D15, // C29 - Fuel Pump
	Gpio::G7, // E1 - LS1
	Gpio::G8, // E2- LS2
	Gpio::D11, // E3 - LS3
	Gpio::D10, // E4 - LS4/VVT
	Gpio::D9, // E13 - INJ 4
	Gpio::F12, // E14 - INJ 2
	Gpio::F13, // E25 - INJ 1
	Gpio::F14, // E26 - INJ 3
	Gpio::H15, // P34_OUT_LOW8
	Gpio::E2, // F4 - IGN 5
	Gpio::E4, // F6 - IGN 3
	Gpio::I6, // F9 - IGN 7
	Gpio::I7, // F11 - IGN 8
	Gpio::E3, // F13 - IGN 4
	Gpio::E5, // F16 - IGN 2
	Gpio::I5, // F17 - IGN 6
	Gpio::I8, // F20 - IGN 1
// "P19_OUT_LOW11",
// "P35_OUT_LOW9",
// "P33_PWM5",
// "P18_OUT_PP2",
// "A6 - Fan Control",
// "C21 - Evap Purge Control",
// "C29 - Fuel Pump",
// "E1 - LS1",
// "E2- LS2",
// "E3 - LS3",
// "E4 - LS4/VVT",
// "E13 - INJ 4",
// "E14 - INJ 2",
// "E25 - INJ 1",
// "E26 - INJ 3",
// "P34_OUT_LOW8",
// "F4 - IGN 5",
// "F6 - IGN 3",
// "F9 - IGN 7",
// "F11 - IGN 8",
// "F13 - IGN 4",
// "F16 - IGN 2",
// "F17 - IGN 6",
// "F20 - IGN 1",
}
