//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-8chan-revA/connectors/8chan-A-B.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-8chan-revA/connectors/8chan-C.yaml
// auto-generated by PinoutLogic.java based on config/boards/hellen/alphax-8chan-revA/connectors/8chan-D.yaml
#pragma once

#define PIN_On-board MAP EFI_ADC_11
#define PIN_1A D10
#define PIN_8A A10
#define PIN_14B F3
