//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellenMiataNA6/connectors/main.yaml
#pragma once

#define PIN_1B EFI_ADC_5
#define PIN_1E G9
#define PIN_1G_rev_c I8
#define PIN_1G C13
#define PIN_1H E5
#define PIN_1J H15
#define PIN_1L D12
#define PIN_1M F11
#define PIN_1Q_switch_inputs C5
#define PIN_1Q_analog_inputs EFI_ADC_15
#define PIN_1V_switch_inputs C4
#define PIN_1V_analog_inputs EFI_ADC_14
#define PIN_2I F14
#define PIN_2J F12
#define PIN_2L F3
#define PIN_2M_switch_inputs C1
#define PIN_2M_analog_inputs EFI_ADC_11
#define PIN_2N_switch_inputs A1
#define PIN_2N_analog_inputs EFI_ADC_1
#define PIN_3E B1
#define PIN_3G A6
#define PIN_3I_rev_C I0
#define PIN_3I G12
#define PIN_3M EFI_ADC_4
#define PIN_3O EFI_ADC_10
#define PIN_3P EFI_ADC_13
#define PIN_3S D9
#define PIN_3T G2
#define PIN_3N EFI_ADC_0
#define PIN_3Q EFI_ADC_12
#define PIN_3U G7
#define PIN_3V G8
#define PIN_3W D14
#define PIN_3Y D11
#define PIN_3Z D10
#define PIN_int_map EFI_ADC_2
#define PIN_4G_switch_inputs A7
#define PIN_4G_analog_inputs EFI_ADC_7
#define PIN_4H_switch_inputs B0
#define PIN_4H_analog_inputs EFI_ADC_8
#define PIN_4I_switch_inputs A3
#define PIN_4I_analog_inputs EFI_ADC_3
#define PIN_int_etb+ C7
#define PIN_int_etb_ C8
#define PIN_int_etb_EN C6
