//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/hellen/hellenMiataNA6/connectors/main.yaml
#pragma once

#define PIN_1B EFI_ADC_5
#define PIN_1E G9
#define PIN_1M F11
#define PIN_1Q C5
