//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on config/boards/m74_9/connectors/m74_9.yaml
#pragma once

#define PIN_AA1 F8
#define PIN_AC2 F6
#define PIN_AC3 EFI_ADC_1
#define PIN_AC4 L9779_OUT_6
