// This file was generated by Version2Header
// Fri Feb 18 01:13:10 UTC 2022


#ifndef GIT_HASH
#define GIT_HASH "9a8b5b510e29bcd1a4269da68aaef63ddfc4135f"
#endif


#ifndef VCS_VERSION
#define VCS_VERSION "36827"
#endif
