// This file was generated by Version2Header
// Tue Jan 24 00:23:39 UTC 2023


#ifndef GIT_HASH
#define GIT_HASH "399f280e9d7df3204d5b75371b95f7d6346d92b3"
#endif


#ifndef VCS_VERSION
#define VCS_VERSION "52573"
#endif
