// auto-generated by PinoutLogic.java

#include "pch.h"

const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case GPIOA_6: return "79 - IN_CAM";
		case GPIOA_7: return "77 - IN_AUX4";
		case GPIOA_9: return "28 - OUT_O2H2";
		case GPIOB_0: return "74 - IN_AUX1";
		case GPIOB_1: return "15 - IN_CRANK (A24)";
		case GPIOB_8: return "23 - IGN_6";
		case GPIOB_9: return "22 - IGN_7";
		case GPIOC_4: return "75 - IN_AUX2";
		case GPIOC_5: return "76 - IN_AUX3";
		case GPIOC_6: return "67 - OUT_COIL_A1";
		case GPIOC_7: return "66 - OUT_COIL_A2";
		case GPIOC_8: return "65 - OUT_COIL_B1";
		case GPIOC_9: return "64 - OUT_COIL_B2";
		case GPIOD_10: return "47 - INJ_4";
		case GPIOD_11: return "7 - INJ_3";
		case GPIOD_12: return "68 - OUT_ECF";
		case GPIOD_13: return "60 - OUT_IO";
		case GPIOD_14: return "8 - OUT_TACH";
		case GPIOD_15: return "10 - OUT_FUEL";
		case GPIOD_9: return "30 - INJ_5";
		case GPIOE_2: return "24 - IGN_5";
		case GPIOE_3: return "4 - IGN_4";
		case GPIOE_4: return "2 - IGN_3";
		case GPIOE_5: return "1 - IGN_2";
		case GPIOE_6: return "21 - IGN_8";
		case GPIOF_11: return "59 - IN_VSS";
		case GPIOF_12: return "25 - INJ_6";
		case GPIOF_13: return "72 - INJ_7";
		case GPIOF_14: return "73 - INJ_8";
		case GPIOF_5: return "9 - IN_SENS3";
		case GPIOG_2: return "70 - OUT_PUMP";
		case GPIOG_3: return "46 - OUT_CANIST";
		case GPIOG_4: return "31 - OUT_CE";
		case GPIOG_7: return "27 - INJ_1";
		case GPIOG_8: return "6 - INJ_2";
		case GPIOH_13: return "11 - OUT_HIGH";
		case GPIOH_14: return "48 - OUT_O2H";
		case GPIOH_15: return "69 - OUT_AC";
		case GPIOI_0: return "50 - OUT_STARTER";
		case GPIOI_1: return "49 - OUT_HEATER";
		case GPIOI_2: return "14 - OUT_MAIN";
		case GPIOI_8: return "5 - IGN_1";
		default: return nullptr;
	}
	return nullptr;
}
