

ifeq ($(LED_CRITICAL_ERROR_BRAIN_PIN),)
  LED_CRITICAL_ERROR_BRAIN_PIN = -DLED_CRITICAL_ERROR_BRAIN_PIN=H64_LED1_RED
endif

DDEFS += $(LED_CRITICAL_ERROR_BRAIN_PIN)

PRIMARY_COMMUNICATION_PORT_USART3=-DEFI_CONSOLE_TX_BRAIN_PIN=Gpio::C10 -DEFI_CONSOLE_RX_BRAIN_PIN=Gpio::C11 -DTS_PRIMARY_UxART_PORT=UARTD3 -DSTM32_UART_USE_USART3=1

DDEFS += -DHELLEN_BOARD_ID_PIN_1=Gpio::C2 -DHELLEN_BOARD_ID_PIN_2=Gpio::C3

include $(BOARDS_DIR)/hellen/hellen-common.mk
