
# 144 package MCU
ifeq ($(LED_CRITICAL_ERROR_BRAIN_PIN),)
# H144_LED1_RED is Gpio::G0
  LED_CRITICAL_ERROR_BRAIN_PIN = -DLED_CRITICAL_ERROR_BRAIN_PIN=Gpio::G0
endif

DDEFS += $(LED_CRITICAL_ERROR_BRAIN_PIN)

DDEFS += -DHELLEN_BOARD_ID_PIN_1=Gpio::F0 -DHELLEN_BOARD_ID_PIN_2=Gpio::F1

BOARDCPPSRC += $(BOARDS_DIR)/hellen/hellen_leds_144.cpp
include $(BOARDS_DIR)/hellen/hellen-common.mk
